import React from 'react';
import {
  MessageSquare, Globe, Radio, Phone, Mail, Smartphone, Tablet, Camera, Send, Tv2
} from 'lucide-react';

// ─── Bilingual Translation Dictionary ─────────────────────────────────────────
export const DICT = {
  en: {
    title: 'Omnichannel Channels',
    description: 'Manage communication channel integrations and provider credentials across the platform.',
    activeChannels: 'Active Channels',
    connectedProviders: 'Connected Providers',
    messagesToday: 'Messages Today',
    failedDeliveries: 'Failed Deliveries',
    queueThroughput: 'Queue Throughput',
    aiAutomationRate: 'AI Automation Rate',
    catalogTitle: 'Channel Catalog',
    catalogDesc: 'Web / WhatsApp / SMS / Voice / Email / iOS / Android and social channels — connectivity, routing, and real-time health.',
    catalogTableTitle: 'Communication Channels',
    catalogTableDesc: 'Full channel topology with provider bindings, routing policies, and operational parameters.',
    credTitle: 'Provider Credentials',
    credDesc: 'Twilio / Meta / Plivo / SendGrid / SIP Trunk — API keys, webhook endpoints, authentication, and sync status.',
    providerIntegrationsTitle: 'Provider Integrations',
    providerIntegrationsDesc: 'Manage security credentials, authorization endpoints, and system status across external communication providers.',
    liveTrafficTitle: 'Live Traffic & Delivery Health',
    liveTrafficDesc: 'Real-time throughput, webhook status, and latency indicators per active channel.',
    aiRoutingTitle: 'AI Routing & Automation',
    aiRoutingDesc: 'Configure intelligent routing thresholds, escalation rules, and per-channel automation policies.',
    colChannel: 'Channel',
    colProvider: 'Provider',
    colStatus: 'Status',
    colRegion: 'Region',
    colAI: 'AI Enabled',
    colRouting: 'Routing Policy',
    colFailover: 'Failover',
    colLastSync: 'Last Sync',
    colActions: 'Actions',
    colProviderName: 'Provider',
    colAuthType: 'Auth Type',
    colApiKey: 'API Key',
    colWebhook: 'Webhook URL',
    colEnvironment: 'Environment',
    colFailoverProv: 'Failover',
    colRegionProv: 'Region',
    colSyncStatus: 'Sync Status',
    colLastValidated: 'Last Validated',
    channelConfigTitle: 'Channel Configuration',
    apiKeyLabel: 'API Key / Secret',
    webhookLabel: 'Webhook Endpoint URL',
    rateLimitLabel: 'Rate Limit (msg/s)',
    failoverLabel: 'Failover Channel',
    modeLabel: 'Environment Mode',
    sandbox: 'Sandbox',
    live: 'Live',
    save: 'Save Configuration',
    cancel: 'Cancel',
    providerConfigTitle: 'Provider Credentials',
    uptime: 'Uptime',
    latency: 'Latency',
    throughput: 'Throughput',
    failedWebhooks: 'Failed Webhooks',
    deliveryHealth: 'Delivery Health',
    enabled: 'Enabled',
    disabled: 'Disabled',
    configure: 'Configure',
    refreshSync: 'Sync',
    viewCredentials: 'Credentials',
    active: 'Active',
    inactive: 'Inactive',
    routingState: 'Routing State',
    testConnection: 'Test Connection',
    connectionSuccess: 'Ping: 42ms (Healthy)',
    connectionTesting: 'Testing...',
    revisionHistory: 'Credential Revision History',
    rollback: 'Rollback',
    colVersion: 'Version',
    colModifiedBy: 'Modified By',
    colDate: 'Date',
  },
  ar: {
    title: 'القنوات متعددة القنوات',
    description: 'إدارة تكاملات قنوات الاتصال وبيانات اعتماد الموفرين عبر المنصة.',
    activeChannels: 'القنوات النشطة',
    connectedProviders: 'الموفرون المتصلون',
    messagesToday: 'رسائل اليوم',
    failedDeliveries: 'عمليات التسليم الفاشلة',
    queueThroughput: 'إنتاجية قائمة الانتظار',
    aiAutomationRate: 'معدل أتمتة الذكاء الاصطناعي',
    catalogTitle: 'كتالوج القنوات',
    catalogDesc: 'ويب / واتساب / رسائل SMS / صوت / بريد إلكتروني / iOS / Android والقنوات الاجتماعية.',
    catalogTableTitle: 'قنوات الاتصال',
    catalogTableDesc: 'طبولوجيا القناة الكاملة مع ارتباطات الموفر وسياسات التوجيه والمعاملات التشغيلية.',
    credTitle: 'بيانات اعتماد الموفر',
    credDesc: 'Twilio / Meta / Plivo / SendGrid / SIP Trunk — مفاتيح API ونقاط نهاية Webhook والمصادقة.',
    providerIntegrationsTitle: 'تكاملات موفري الخدمة',
    providerIntegrationsDesc: 'إدارة بيانات اعتماد الأمان ونقاط نهاية المصادقة وحالة النظام عبر موفري الاتصالات الخارجيين.',
    liveTrafficTitle: 'حركة المرور المباشرة وصحة التسليم',
    liveTrafficDesc: 'مقاييس الإنتاجية في الوقت الفعلي وحالة Webhook ومؤشرات زمن الوصول.',
    aiRoutingTitle: 'التوجيه والأتمتة بالذكاء الاصطناعي',
    aiRoutingDesc: 'تكوين عتبات التوجيه الذكي وقواعد التصعيد وسياسات الأتمتة لكل قناة.',
    colChannel: 'القناة',
    colProvider: 'الموفر',
    colStatus: 'الحالة',
    colRegion: 'المنطقة',
    colAI: 'الذكاء الاصطناعي',
    colRouting: 'سياسة التوجيه',
    colFailover: 'التعافي',
    colLastSync: 'آخر مزامنة',
    colActions: 'الإجراءات',
    colProviderName: 'الموفر',
    colAuthType: 'نوع المصادقة',
    colApiKey: 'مفتاح API',
    colWebhook: 'Webhook',
    colEnvironment: 'البيئة',
    colFailoverProv: 'التعافي',
    colRegionProv: 'المنطقة',
    colSyncStatus: 'حالة المزامنة',
    colLastValidated: 'آخر تحقق',
    channelConfigTitle: 'تكوين القناة',
    apiKeyLabel: 'مفتاح API / السر',
    webhookLabel: 'عنوان Webhook',
    rateLimitLabel: 'حد المعدل (رسالة/ثانية)',
    failoverLabel: 'قناة التعافي',
    modeLabel: 'وضع البيئة',
    sandbox: 'بيئة الاختبار',
    live: 'مباشر',
    save: 'حفظ التكوين',
    cancel: 'إلغاء',
    providerConfigTitle: 'بيانات اعتماد الموفر',
    uptime: 'وقت التشغيل',
    latency: 'زمن الوصول',
    throughput: 'الإنتاجية',
    failedWebhooks: 'Webhooks الفاشلة',
    deliveryHealth: 'صحة التسليم',
    enabled: 'مفعّل',
    disabled: 'معطّل',
    configure: 'تكوين',
    refreshSync: 'مزامنة',
    viewCredentials: 'بيانات الاعتماد',
    active: 'نشط',
    inactive: 'غير نشط',
    routingState: 'حالة التوجيه',
    testConnection: 'اختبار الاتصال',
    connectionSuccess: 'استجابة: 42ms (سليم)',
    connectionTesting: 'جاري الاختبار...',
    revisionHistory: 'سجل مراجعة بيانات الاعتماد',
    rollback: 'تراجع',
    colVersion: 'الإصدار',
    colModifiedBy: 'بواسطة',
    colDate: 'التاريخ',
  },
};

// ─── Section A: Channel Catalog Seed Data ────────────────────────────────────
export const CHANNELS = [
  {
    id: 'ch-wa',
    name: 'WhatsApp Business',
    icon: <MessageSquare className="w-4 h-4 text-emerald-500" />,
    iconBg: 'bg-emerald-500/10',
    accentColor: 'bg-emerald-500',
    providerKey: 'twilio',
    provider: 'Twilio WhatsApp Business API',
    status: 'operational',
    region: 'ME-Central-1 (Dubai)',
    aiEnabled: true,
    routingPolicy: 'Round-Robin + AI Triage',
    failover: 'SMS Fallback',
    lastSync: '2 min ago',
    uptime: '99.97%',
    latencyMs: 142,
    msgPerSec: 88,
    failedWebhooks: 0,
    deliveryHealth: 99.8,
    apiKey: 'twilio_sk_live_••••••••••••••••••••••XKQJ',
    webhook: 'https://api.mp-core.ai/webhooks/whatsapp',
    rateLimit: 120,
    failoverChannel: 'SMS',
    mode: 'live' as 'live' | 'sandbox',
  },
  {
    id: 'ch-wc',
    name: 'Web Chat Widget',
    icon: <Globe className="w-4 h-4 text-sky-500" />,
    iconBg: 'bg-sky-500/10',
    accentColor: 'bg-sky-500',
    providerKey: 'native',
    provider: 'Native mPaaS SDK (WebSocket)',
    status: 'operational',
    region: 'Global CDN (CloudFront)',
    aiEnabled: true,
    routingPolicy: 'AI-First + Human Escalation',
    failover: 'Email Ticket',
    lastSync: 'Just now',
    uptime: '100%',
    latencyMs: 55,
    msgPerSec: 210,
    failedWebhooks: 0,
    deliveryHealth: 100,
    apiKey: 'wc_sdk_prod_••••••••••••••••••••••••••••••',
    webhook: 'wss://api.mp-core.ai/ws/chat',
    rateLimit: 300,
    failoverChannel: 'Email',
    mode: 'live' as 'live' | 'sandbox',
  },
  {
    id: 'ch-sm',
    name: 'SMS',
    icon: <Radio className="w-4 h-4 text-amber-500" />,
    iconBg: 'bg-amber-500/10',
    accentColor: 'bg-amber-500',
    providerKey: 'twilio',
    provider: 'Twilio SMS Programmable',
    status: 'degraded',
    region: 'US-East-1 (Virginia)',
    aiEnabled: false,
    routingPolicy: 'Broadcast (Notification Only)',
    failover: 'WhatsApp',
    lastSync: '18 min ago',
    uptime: '97.40%',
    latencyMs: 820,
    msgPerSec: 34,
    failedWebhooks: 7,
    deliveryHealth: 94.2,
    apiKey: 'AC••••••••••••••••••••••••••••••B3D7',
    webhook: 'https://api.mp-core.ai/webhooks/sms',
    rateLimit: 40,
    failoverChannel: 'WhatsApp',
    mode: 'live' as 'live' | 'sandbox',
  },
  {
    id: 'ch-vo',
    name: 'Voice / SIP',
    icon: <Phone className="w-4 h-4 text-blue-500" />,
    iconBg: 'bg-blue-500/10',
    accentColor: 'bg-blue-500',
    providerKey: 'twilio',
    provider: 'Twilio Elastic SIP Trunking',
    status: 'operational',
    region: 'ME-Central-1 (Dubai)',
    aiEnabled: true,
    routingPolicy: 'Skill-Based (NLP Intent)',
    failover: 'WhatsApp Callback',
    lastSync: '1 min ago',
    uptime: '99.85%',
    latencyMs: 68,
    msgPerSec: 18,
    failedWebhooks: 0,
    deliveryHealth: 99.9,
    apiKey: 'AC••••••••••••••••••••••••••••••2F91',
    webhook: 'https://api.mp-core.ai/webhooks/voice',
    rateLimit: 25,
    failoverChannel: 'WhatsApp',
    mode: 'live' as 'live' | 'sandbox',
  },
  {
    id: 'ch-em',
    name: 'Email',
    icon: <Mail className="w-4 h-4 text-violet-500" />,
    iconBg: 'bg-violet-500/10',
    accentColor: 'bg-violet-500',
    providerKey: 'sendgrid',
    provider: 'SendGrid Enterprise SMTP',
    status: 'operational',
    region: 'EU-West-1 (Frankfurt)',
    aiEnabled: true,
    routingPolicy: 'Priority Queue (SLA-based)',
    failover: 'SMTP Direct',
    lastSync: '5 min ago',
    uptime: '99.91%',
    latencyMs: 310,
    msgPerSec: 42,
    failedWebhooks: 2,
    deliveryHealth: 98.6,
    apiKey: 'SG.••••••••••••••••••••••••••••••••••••••••',
    webhook: 'https://api.mp-core.ai/webhooks/email',
    rateLimit: 50,
    failoverChannel: 'Web Chat',
    mode: 'live' as 'live' | 'sandbox',
  },
  {
    id: 'ch-ios',
    name: 'iOS Mobile SDK',
    icon: <Smartphone className="w-4 h-4 text-slate-500" />,
    iconBg: 'bg-slate-500/10',
    accentColor: 'bg-slate-500',
    providerKey: 'native',
    provider: 'Native mPaaS iOS SDK (APNs)',
    status: 'operational',
    region: 'Global (APNs Gateway)',
    aiEnabled: true,
    routingPolicy: 'AI-First + Push Fallback',
    failover: 'Web Chat',
    lastSync: '3 min ago',
    uptime: '99.80%',
    latencyMs: 90,
    msgPerSec: 65,
    failedWebhooks: 0,
    deliveryHealth: 99.5,
    apiKey: 'apns_key_••••••••••••••••••••••••••••••',
    webhook: 'https://api.mp-core.ai/webhooks/ios',
    rateLimit: 100,
    failoverChannel: 'Web Chat',
    mode: 'live' as 'live' | 'sandbox',
  },
  {
    id: 'ch-android',
    name: 'Android Mobile SDK',
    icon: <Tablet className="w-4 h-4 text-green-600" />,
    iconBg: 'bg-green-600/10',
    accentColor: 'bg-green-600',
    providerKey: 'native',
    provider: 'Native mPaaS Android SDK (FCM)',
    status: 'operational',
    region: 'Global (FCM Gateway)',
    aiEnabled: true,
    routingPolicy: 'AI-First + Push Fallback',
    failover: 'Web Chat',
    lastSync: '3 min ago',
    uptime: '99.75%',
    latencyMs: 105,
    msgPerSec: 71,
    failedWebhooks: 0,
    deliveryHealth: 99.3,
    apiKey: 'fcm_server_key_••••••••••••••••••••••••••',
    webhook: 'https://api.mp-core.ai/webhooks/android',
    rateLimit: 100,
    failoverChannel: 'Web Chat',
    mode: 'live' as 'live' | 'sandbox',
  },
  {
    id: 'ch-ig',
    name: 'Instagram DM',
    icon: <Camera className="w-4 h-4 text-pink-500" />,
    iconBg: 'bg-pink-500/10',
    accentColor: 'bg-pink-500',
    providerKey: 'meta',
    provider: 'Meta Business Graph API v19',
    status: 'operational',
    region: 'EU-West-1 (Dublin)',
    aiEnabled: true,
    routingPolicy: 'AI Triage + Round-Robin',
    failover: 'Facebook Messenger',
    lastSync: '8 min ago',
    uptime: '99.60%',
    latencyMs: 195,
    msgPerSec: 28,
    failedWebhooks: 1,
    deliveryHealth: 99.1,
    apiKey: 'EAAl••••••••••••••••••••••••••••••••BAZA',
    webhook: 'https://api.mp-core.ai/webhooks/instagram',
    rateLimit: 35,
    failoverChannel: 'FB Messenger',
    mode: 'live' as 'live' | 'sandbox',
  },
  {
    id: 'ch-fb',
    name: 'Facebook Messenger',
    icon: <Tv2 className="w-4 h-4 text-blue-600" />,
    iconBg: 'bg-blue-600/10',
    accentColor: 'bg-blue-600',
    providerKey: 'meta',
    provider: 'Meta Business Graph API v19',
    status: 'operational',
    region: 'EU-West-1 (Dublin)',
    aiEnabled: true,
    routingPolicy: 'Intent-Based Routing (NLU)',
    failover: 'Instagram DM',
    lastSync: '8 min ago',
    uptime: '99.55%',
    latencyMs: 210,
    msgPerSec: 22,
    failedWebhooks: 1,
    deliveryHealth: 98.8,
    apiKey: 'EAAl••••••••••••••••••••••••••••••••C71X',
    webhook: 'https://api.mp-core.ai/webhooks/messenger',
    rateLimit: 30,
    failoverChannel: 'Instagram',
    mode: 'live' as 'live' | 'sandbox',
  },
  {
    id: 'ch-tg',
    name: 'Telegram Bot',
    icon: <Send className="w-4 h-4 text-cyan-500" />,
    iconBg: 'bg-cyan-500/10',
    accentColor: 'bg-cyan-500',
    providerKey: 'telegram',
    provider: 'Telegram Bot API v7.2',
    status: 'inactive',
    region: 'EU-Central-1 (Frankfurt)',
    aiEnabled: false,
    routingPolicy: 'Command-Based (Bot Mode)',
    failover: 'Web Chat',
    lastSync: '2 hours ago',
    uptime: '91.20%',
    latencyMs: 480,
    msgPerSec: 5,
    failedWebhooks: 14,
    deliveryHealth: 87.3,
    apiKey: 'bot••••••••••••••••••••••••••••••:AAXX••',
    webhook: 'https://api.mp-core.ai/webhooks/telegram',
    rateLimit: 10,
    failoverChannel: 'Web Chat',
    mode: 'sandbox' as 'live' | 'sandbox',
  },
];

// ─── Section B: Provider Credentials Seed Data ───────────────────────────────
export const PROVIDERS = [
  {
    id: 'prov-twilio',
    name: 'Twilio',
    logoColor: 'text-red-500',
    logoBg: 'bg-red-500/10',
    authType: 'Account SID + Auth Token',
    apiKey: 'AC••••••••••••••••••••••••••••••XKQJ',
    webhook: 'https://api.mp-core.ai/webhooks/twilio',
    environment: 'live' as 'live' | 'sandbox',
    failover: 'Plivo',
    region: 'ME-Central-1 (Dubai)',
    syncStatus: 'synced',
    lastValidated: '4 min ago',
    channels: ['WhatsApp Business', 'SMS', 'Voice / SIP'],
  },
  {
    id: 'prov-meta',
    name: 'Meta Business API',
    logoColor: 'text-blue-600',
    logoBg: 'bg-blue-600/10',
    authType: 'OAuth 2.0 + App Secret',
    apiKey: 'EAAl••••••••••••••••••••••••••••••••META',
    webhook: 'https://api.mp-core.ai/webhooks/meta',
    environment: 'live' as 'live' | 'sandbox',
    failover: 'Web Chat',
    region: 'EU-West-1 (Dublin)',
    syncStatus: 'synced',
    lastValidated: '9 min ago',
    channels: ['Facebook Messenger', 'Instagram DM'],
  },
  {
    id: 'prov-plivo',
    name: 'Plivo',
    logoColor: 'text-orange-500',
    logoBg: 'bg-orange-500/10',
    authType: 'Auth ID + Auth Token',
    apiKey: 'MAND••••••••••••••••••••••••••••••••PLVO',
    webhook: 'https://api.mp-core.ai/webhooks/plivo',
    environment: 'sandbox' as 'live' | 'sandbox',
    failover: 'Twilio',
    region: 'AP-South-1 (Mumbai)',
    syncStatus: 'pending',
    lastValidated: '2 hours ago',
    channels: ['SMS', 'Voice / SIP'],
  },
  {
    id: 'prov-sendgrid',
    name: 'SendGrid',
    logoColor: 'text-violet-500',
    logoBg: 'bg-violet-500/10',
    authType: 'API Key (Bearer)',
    apiKey: 'SG.••••••••••••••••••••••••••••••••••••••••',
    webhook: 'https://api.mp-core.ai/webhooks/email',
    environment: 'live' as 'live' | 'sandbox',
    failover: 'SMTP Direct',
    region: 'EU-West-1 (Frankfurt)',
    syncStatus: 'synced',
    lastValidated: '6 min ago',
    channels: ['Email'],
  },
  {
    id: 'prov-sip',
    name: 'SIP Trunk',
    logoColor: 'text-blue-500',
    logoBg: 'bg-blue-500/10',
    authType: 'SIP Digest (Username + Password)',
    apiKey: 'sip_trunk_••••••••••••••••••••••••••••',
    webhook: 'sip:gateway.mp-core.ai:5060',
    environment: 'live' as 'live' | 'sandbox',
    failover: 'WhatsApp Callback',
    region: 'ME-Central-1 (Dubai)',
    syncStatus: 'synced',
    lastValidated: '2 min ago',
    channels: ['Voice / SIP'],
  },
  {
    id: 'prov-exotel',
    name: 'Exotel',
    logoColor: 'text-teal-500',
    logoBg: 'bg-teal-500/10',
    authType: 'API Key + API Token',
    apiKey: 'exo_api_••••••••••••••••••••••••••••••',
    webhook: 'https://api.mp-core.ai/webhooks/exotel',
    environment: 'sandbox' as 'live' | 'sandbox',
    failover: 'Twilio',
    region: 'AP-South-1 (Mumbai)',
    syncStatus: 'error',
    lastValidated: '3 hours ago',
    channels: ['SMS', 'Voice / SIP'],
  },
];

export const AI_ROUTING_SETTINGS = [
  { id: 'auto_routing', label: 'AI Auto-Routing', labelAr: 'التوجيه التلقائي بالذكاء الاصطناعي', enabled: true, desc: 'Automatically route inbound contacts to the best-fit agent based on NLU intent classification.', descAr: 'توجيه جهات الاتصال الواردة تلقائيًا إلى أفضل وكيل بناءً على تصنيف النية.' },
  { id: 'fallback_human', label: 'Fallback to Human', labelAr: 'التحويل إلى الإنسان', enabled: true, desc: 'Trigger human escalation when AI confidence drops below 0.65 or NPS sentiment is negative.', descAr: 'تفعيل التصعيد البشري عندما تنخفض ثقة الذكاء الاصطناعي أو يكون الإنطباع سلبياً.' },
  { id: 'multilingual', label: 'Multilingual Routing', labelAr: 'التوجيه متعدد اللغات', enabled: true, desc: 'Detect customer language on first interaction and route to matching bilingual agents (AR/EN).', descAr: 'اكتشاف لغة العميل في أول تفاعل وتوجيهه إلى الوكلاء الثنائيين المناسبين.' },
  { id: 'escalation', label: 'Escalation Threshold', labelAr: 'عتبة التصعيد', enabled: true, desc: 'Escalate to Tier-2 supervisor when 3+ failed resolution attempts are detected within 10 min.', descAr: 'التصعيد إلى المشرف عند اكتشاف 3+ محاولات حل فاشلة في غضون 10 دقائق.' },
  { id: 'ch_automation', label: 'Per-Channel Automation', labelAr: 'أتمتة لكل قناة', enabled: false, desc: 'Enable channel-specific bot automation policies overriding global AI routing defaults.', descAr: 'تمكين سياسات أتمتة البوت الخاصة بالقناة بدلاً من الإعدادات الافتراضية.' },
];
