import re

ar_path = "/Users/sudhir88/Desktop/CustomerSelfService/src/i18n/ar.ts"

with open(ar_path, 'r', encoding='utf-8') as f:
    ar_content = f.read()

# Let's verify where the portal namespace starts and ends.
# We want to keep everything before myTickets' closing brace, and then insert the new portal keys.
# Let's search for myTickets block inside portal in ar_content:
pattern = r"(myTickets:\s*\{[^}]*emptyDesc:\s*'[م|ل|ت|و|ج|د|أ|ب|ل|ا|غ|ا|ت| |د|ع|م| |ف|ن|ي| |ح|ت|ى| |ا|ل|آ|ن|\.]*'\s*\})"
match = re.search(pattern, ar_content)

if not match:
    # Let's do a simpler match
    pattern = r"(myTickets:\s*\{[^}]*\})"
    match = re.search(pattern, ar_content)

if match:
    print("Found myTickets block!")
    my_tickets_end = match.end()
    # Everything up to myTickets block (including its closing brace)
    base_ar = ar_content[:my_tickets_end]
    
    # Let's append the new portal namespaces, close portal, and add dialogFlow and analyticsCenter
    new_portal_namespaces = """,
    chatHistory: {
      title: 'سجل المحادثات المنتهية والمحلولة',
      subtitle: 'اطلع على سجلات المحادثات السابقة التي تم حلها مع فريق الدعم.',
      chatId: 'معرف المحادثة:',
      solved: 'تاريخ الحل:',
      agent: 'الوكيل:'
    },
    accessibility: {
      modalTitle: 'أدوات إمكانية الوصول',
      highContrast: 'نمط التباين العالي',
      enabled: 'مفعّل',
      disabled: 'معطّل',
      fontSizeLabel: 'مستوى تكبير النص',
      fontSmall: 'صغير',
      fontNormal: 'عادي',
      fontLarge: 'كبير',
      keyboardHint: 'اختصارات لوحة المفاتيح: استخدم مفتاح Tab للتنقل بين العناصر، واضغط Enter لتحديد الأزرار.'
    },
    callback: {
      modalTitle: 'جدولة مكالمة استجواب خارجية',
      phoneLabel: 'رقم هاتف الاتصال المباشر',
      timeLabel: 'الإطار الزمني المفضل للمكالمة',
      timeSoonest: 'في أقرب وقت ممكن (خلال 15 دقيقة)',
      timeMorning: 'صباحاً (09:00 - 12:00)',
      timeAfternoon: 'ظهراً (12:00 - 15:00)',
      timeEvening: 'مساءً (15:00 - 18:00)',
      cancel: 'إلغاء',
      book: 'تأكيد حجز المكالمة'
    },
    cobrowse: {
      modalTitle: 'الانضمام إلى جلسة التصفح المشترك',
      instructions: 'أنشئ جلسة مشاركة شاشة آمنة. سيطلب منك الوكيل هذا الرمز المكوّن من 6 أرقام للتحقق والاستشارة.',
      sessionActive: 'الجلسة نشطة (الشاشة مشاركة)',
      pinLabel: 'أدخل الرمز المكوّن من 6 أرقام (مثال: 982-114)',
      connect: 'إنشاء اتصال المشاركة'
    },
    voiceCall: {
      modalTitle: 'خطوط ساخنة لمركز الاتصال',
      instructions: 'اتصل مباشرة عبر خط بوابة الاتصال الصوتي SIP VoIP الآمن الخاص بنا عن طريق طلب الخط الساخن أدناه:'
    },
    liveChat: {
      botName: 'فرح - الدعم الذكي',
      botSubtitle: 'بوابة بوت متعددة القنوات',
      farahTyping: 'فرح تكتب...',
      routingToAgent: 'جاري التوجيه إلى وكيل مباشر...',
      queuePosition: 'موضعك في قائمة الانتظار:',
      estimatedWait: 'الوقت التقديري للانتظار:',
      mins: 'دقيقة',
      csatTitle: 'استبيان رضا العملاء (CSAT)',
      csatSubtitle: 'كيف كانت تجربتك مع الوكيلة ناديا فانس؟',
      npsTitle: 'مؤشر صافي المروجين (NPS)',
      npsScale: 'المقياس من 1 (أدنى) إلى 10 (أعلى)',
      submitSurvey: 'إرسال نتائج الاستبيان',
      surveyThankYou: 'شكراً لك!',
      surveyLogged: 'تم تسجيل ملاحظاتك على المحادثة.',
      emailTranscriptTitle: 'إرسال سجل المحادثة عبر البريد',
      emailLabel: 'عنوان البريد الإلكتروني',
      sendTranscript: 'إرسال سجل المحادثة',
      transcriptSent: 'تم الإرسال!',
      transcriptDispatchedTo: 'تم الإرسال إلى',
      inputPlaceholder: 'اكتب رسالة أو اضغط على \\'وكيل\\'...',
      closeChat: 'إغلاق',
      agentButton: 'وكيل'
    },
    refunds: {
      title: 'بوابة البحث عن الطلبات والاسترجاع',
      subtitle: 'التحقق من الطلبات ومعالجة استثناءات الاسترجاع.',
      otpTitle: 'التحقق الآمن من الطلب (OTP)',
      otpEmailInstructions: 'يرجى إدخال بريدك الإلكتروني المسجل لإرسال رمز التحقق المكون من 4 أرقام.',
      corporateEmail: 'البريد الإلكتروني للشركة',
      sendCode: 'إرسال رمز التحقق',
      otpCodeInstructions: 'لقد أرسلنا رمز تحقق إلى {email}. أدخل الرمز أدناه (استخدم الرمز 1234).',
      verificationCode: 'رمز التحقق',
      verifyCode: 'التحقق من الرمز',
      orderId: 'معرف الطلب',
      refundEligible: 'مؤهل للاسترداد (خلال 30 يوماً)',
      itemName: 'اسم المنتج',
      purchasedAmount: 'المبلغ المدفوع',
      shipmentDate: 'تاريخ الشحن',
      needReturn: 'هل تحتاج إلى إرجاع هذا المنتج؟',
      returnDesc: 'ابدأ عملية الإرجاع التلقائية. بمجرد التقديم، سيتم تحديث رصيد حسابك الذهبي في غضون 3 أيام عمل.',
      initiateReturn: 'بدء الإرجاع/الاسترداد',
      returnDetails: 'تفاصيل الإرجاع',
      reasonLabel: 'سبب الإرجاع',
      reasonDamaged: 'تالف عند الوصول',
      reasonSla: 'خرق مؤشرات مستوى الخدمة SLA',
      reasonSize: 'حجم العبوة غير صحيح',
      reasonDuplicate: 'حالة فوترة مكررة',
      attachmentLabel: 'تحميل سجلات المرفقات',
      cancel: 'إلغاء',
      submitReturn: 'إرسال تفاصيل الإرجاع',
      confirmTitle: 'تأكيد استثناء الإرجاع',
      confirmDesc: 'يرجى مراجعة معلمات الإرجاع أدناه قبل إرسال مشغلات المزامنة إلى بوابة استثناءات SAP.',
      orderIdLabel: 'معرف الطلب:',
      itemLabel: 'المنتج:',
      returnReasonLabel: 'سبب الإرجاع:',
      uploadedLogsLabel: 'السجلات المحملة:',
      noLogsUploaded: 'لم يتم تحميل سجلات (قواعد التحقق القياسية)',
      editDetails: 'تعديل التفاصيل',
      confirmSubmit: 'تأكيد وإرسال طلب الاسترداد',
      processingSap: 'تشغيل مزامنة استثناءات SAP...',
      processingDesc: 'تقييم مؤشرات أداء مستوى الخدمة SLA مقابل مؤشرات بحث Pinecone...',
      successTitle: 'تم تسجيل طلب الاسترداد',
      successDesc: 'تم طلب الاستثناء بنجاح للمشكلة المحددة. تم تسجيل بيانات اعتماد حسابك للمعالجة.',
      closeWizard: 'إغلاق المعالج',
      logisticsMilestones: 'مراحل الخدمات اللوجستية (مزامنة SAP)',
      milestone1Title: '1. تم تقديم الطلب',
      milestone1Desc: 'تمت الموافقة والتسجيل في Dubai-Core ERP.',
      milestone2Title: '2. تم التحقق من SLA الأداء',
      milestone2Desc: 'تم التحقق من قواعد فحص الاستثناءات.',
      milestone3Title: '3. تم الشحن والمزامنة',
      milestone3Desc: 'تمت مزامنة معرف التتبع مع بوابة العميل.',
      milestone4Title: '4. تم التسليم والتوقيع',
      milestone4Desc: 'تم التوقيع والموافقة من قبل العميل د. ميلر.'
    },
    tickets: {
      modalTitle: 'تقديم بلاغ دعم فني جديد',
      incidentSubject: 'موضوع البلاغ',
      subjectPlaceholder: 'مثال: سجلات نزاع الفوترة',
      category: 'الفئة',
      categoryBilling: 'الفواتير والمدفوعات',
      categoryAuth: 'مصادقة المستخدم',
      categoryApi: 'تكامل واجهات برمجة التطبيقات API',
      categoryShipment: 'الشحن والتوصيل',
      priority: 'الأولوية',
      priorityLow: 'منخفضة',
      priorityMedium: 'متوسطة',
      priorityHigh: 'عالية',
      priorityUrgent: 'عاجل جداً',
      describeIssue: 'شرح تفاصيل المشكلة',
      descPlaceholder: 'يرجى توضيح الخطوات الكاملة لما حدث...',
      cancel: 'إلغاء',
      submitCase: 'إرسال البلاغ',
      pageTitle: 'تقديم بلاغ دعم فني جديد',
      pageSubtitle: 'إنشاء وتتبع بلاغات المشاكل',
      issueLabelFull: 'وصف المشكلة',
      descPlaceholderFull: 'يرجى توضيح الخطوات الكاملة لما حدث، وأي رسائل خطأ، وما كنت تحاول القيام به...',
      descHint: '20 حرفاً كحد أدنى. يرجى تضمين التفاصيل ذات الصلة، أرقام الطلبات، أو رموز الخطأ.',
      submitTicket: 'إرسال بلاغ الدعم الفني',
      whatToExpect: '📌 ماذا تتوقع: سيتم تخصيص رقم مرجعي لبلاغك وتتبعه في قسم "بلاغاتي". سيرد فريق الدعم لدينا في غضون 24 ساعة خلال ساعات العمل الرسمية.',
      listTitle: 'بلاغاتي وحالاتي النشطة',
      listSubtitle: 'متابعة مسار حل البلاغات، والوكلاء المعينين، ومواعيد الـ SLA النهائية.',
      noTickets: 'لا توجد بلاغات دعم فني',
      noTicketsDesc: 'لم تقم بتقديم أي بلاغات دعم فني حتى الآن.',
      openThread: 'فتح المحادثة',
      detailTitle: 'تفاصيل البلاغ',
      detailSubtitle: 'عرض سجل محادثات حل المشكلة',
      ticketNotFound: 'البلاغ غير موجود.',
      openedOn: 'تم فتحه في:',
      conversationHistory: 'سجل المحادثات',
      resolutionFeedback: 'استبيان تقييم حل المشكلة',
      feedbackThankYou: 'شكراً لك على ملاحظاتك وتقييمك!',
      csatLabel: '1. رضا العملاء (CSAT)',
      npsLabel: '2. Net Promoter Score (NPS)',
      npsQuestion: 'ما مدى احتمالية توصيتك بمكتب الدعم لدينا لزميل لك؟',
      commentsLabel: '3. تعليقات إضافية (اختياري)',
      commentsPlaceholder: 'أي شيء آخر تود مشاركته حول هذا الحل...',
      submitFeedback: 'إرسال تقييم الحل',
      caseSpecs: 'مواصفات البلاغ',
      categoryLabel: 'الفئة',
      priorityLabel: 'الأولوية',
      statusLabel: 'حالة الحل',
      statusTimeline: 'مخطط الحالة الزمني',
      timelineOpen: 'تم فتح البلاغ',
      timelineAssigned: 'تم تعيين الوكيل (ليام)',
      pendingAllocation: 'قيد التخصيص والتعيين',
      timelineResolved: 'تم الانتهاء من الحل',
      pendingResolution: 'قيد الحل والمراجعة',
      replyPlaceholder: 'اكتب رداً لإرساله لوكيل الدعم الفني...',
      attachFile: 'إرفاق ملف',
      sendMessage: 'إرسال الرسالة',
      notLikely: 'غير محتمل',
      extremelyLikely: 'محتمل جداً',
      solved: 'تم الحل'
    },
    homeHero: {
      badge: 'مكتب دعم فرح الذكي',
      heroTitle: 'بوابة العميل للخدمة الذاتية',
      heroDesc: 'احصل على حلول فورية من خلال البحث عن معلمات الطلب، أو قراءة أدلة السياسات، أو بدء عمليات الاسترداد التلقائية.',
      searchPlaceholder: 'اكتب استفساراً لجلب الأجزاء المطابقة من RAG (مثل استرداد)...',
      knowledgeHubTitle: 'قاعدة المعرفة',
      knowledgeHubDesc: 'البحث في أجزاء مستندات PDF المخزنة في Pinecone.',
      orderRefundsTitle: 'الطلبات والاسترداد',
      orderRefundsDesc: 'التحقق من تحديثات الطلب وطلب استثناءات المنتجات.',
      submitTicketTitle: 'تقديم بلاغ',
      submitTicketDesc: 'إنشاء وتتبع بلاغات الدعم والمشاكل في أنظمة الـ CRM.',
      voiceSchedulingTitle: 'جدولة المكالمات الصوتية',
      voiceSchedulingDesc: 'حجز موعد مكالمة هاتفية صادرة مع وكلاء الدعم.',
      welcomeBack: 'مرحباً بعودتك، ديفيد ميلر',
      profileBadge: 'الملف الشخصي: corporate-gold-user',
      pastChats: 'المحادثات السابقة',
      coBrowse: 'التصفح المشترك',
      accessibilityOptions: 'خيارات إمكانية الوصول',
      hotline: 'الخط الساخن'
    },
    kbSearch: {
      title: 'البحث في قاعدة المعرفة',
      subtitle: 'البحث عن المقالات المتزامنة من نظام تخزين المتجهات الخاص بنا.',
      categoriesLabel: 'الأقسام والتصنيفات',
      filterPlaceholder: 'تصفية المقالات...',
      noResults: 'لم يتم العثور على أجزاء مطابقة.',
      helpful: 'مفيد',
      catAll: 'الكل',
      catReturns: 'المرتجعات والاسترداد',
      catAccount: 'الحساب والوصول',
      catDev: 'واجهات برمجة المطورين'
    },
    kbArticle: {
      title: 'مقالات قاعدة المعرفة',
      subtitle: 'عرض جزء من مستند RAG',
      articleNotFound: 'المقال غير موجود.',
      helpfulQuestion: 'هل كان هذا المقال مفيداً؟',
      helpfulYes: 'مفيد',
      helpfulNo: 'غير مفيد',
      thankYou: 'شكراً لك على ملاحظاتك وتقييمك!',
      relatedArticles: 'مقالات ذات صلة'
    }
  },

  dialogFlow: {
    layout: {
      mobileInspectorTitle: 'مفتش سير العمل',
      mobileInspectorClose: 'إغلاق',
      simulatorSheetTitle: 'محاكي Farah للتعرف على اللغة الطبيعية',
      simulatorSheetDesc: 'تشغيل محاكاة المحادثة وفحص سجلات التتبع.',
      footerVersion: 'محرك سير عمل mPaaS الذكي: الإصدار 1.8.0-مستقر',
      footerLoadDraft: 'تحميل المسودة المؤقتة',
      footerSaveDraft: 'حفظ المسودة المؤقتة',
    },
    toolbar: {
      panels: 'اللوحات',
      variables: 'المتغيرات',
      simulator: 'المحاكي',
      addNode: 'إضافة عقدة:',
      validateFlow: 'التحقق من التدفق',
      startSim: 'بدء المحاكاة',
      resetSim: 'إعادة تعيين المحاكاة',
      validationOk: 'سلامة البنية الهيكلية لسير العمل صحيحة. جاهز للنشر في خط أنابيب الإنتاج.',
    },
    inspector: {
      variablesContext: 'سياق المتغيرات',
      regressionSuite: 'مجموعة الاختبارات الانحدارية',
      memoryRegister: 'سجل الذاكرة',
      liveTraceMap: 'خريطة التتبع المباشر',
      assertions: 'التأكيدات',
      runAssertionSuite: 'تشغيل مجموعة التأكيدات',
    },
    simulator: {
      title: 'محاكي Farah NLU',
      chatTab: 'المحادثة',
      traceLogs: 'سجلات التتبع',
      idleMessage: 'المحاكي في وضع الخمول. حدد المعاملات المستهدفة في اللوحة واضغط "بدء المحاكاة" لاختبار المتغيرات.',
      startSim: 'بدء المحاكاة',
      stepDebugger: 'مصحح الأخطاء خطوة بخطوة نشط:',
      nextStep: 'الخطوة التالية',
      noTraceLogs: 'لا توجد آثار تنفيذ.',
      executionInProgress: 'التنفيذ جارٍ. انقر على "الخطوة التالية".',
      simulatorWaiting: 'المحاكي ينتظر التهيئة.',
    },
  },

  analyticsCenter: {
    layout: {
      title: 'مركز التحليلات والمراقبة الشاملة',
      subtitle: 'مراقبة أداء محادثات الذكاء الاصطناعي، المكالمات الهاتفية المباشرة، تكامل الأنظمة الخارجية، ومستوى الخدمة.',
      liveStream: 'تدفق القياس المباشر نشط',
      tabExecutive: 'لوحة التحكم التنفيذية',
      tabSla: 'اتفاقيات مستوى الخدمة (SLA)',
      tabWorkforce: 'الموظفين وقنوات الانتظار',
      tabAi: 'مراقبة الذكاء الاصطناعي',
      tabIntegrations: 'ربط الأنظمة والتكامل',
      subWallboard: 'شاشة الاتصالات المباشرة',
      subPerformance: 'أداء الموظفين والخريطة الحرارية',
      subGuardrails: 'حواجز الحماية التوليدية والموجهات',
      subCosts: 'تكاليف الرموز وإخفاقات البحث',
    },
    execDashboard: {
      alertsTitle: 'تحذيرات العمليات المباشرة ومؤشرات مستوى الخدمة',
      kpiPortalTraffic: 'حركة البوابة',
      kpiPortalTrafficSub: 'الجلسات المتتبعة في الوقت الفعلي',
      kpiPortalTrafficTrend: '+18.2% مقارنة بالأسبوع الماضي',
      kpiDeflection: 'انحراف الخدمة الذاتية',
      kpiDeflectionSub: 'تم الحل دون تدخل وكيل',
      kpiDeflectionTarget: 'الهدف: 60.0%',
      kpiSla: 'الالتزام باتفاقية مستوى الخدمة',
      kpiSlaSub: 'الاستجابة والحل',
      kpiSlaGoal: 'الهدف: 98.0%',
      kpiCsat: 'مؤشر الرضا',
      kpiCsatSub: 'متوسط مؤشر رضا العملاء',
      kpiCsatPositive: 'نسبة الإيجابية: 84%',
      funnelTitle: 'قمع تحويل رحلة العميل',
      funnelSubtitle: 'تحويل الانحراف مقابل تراجع إنشاء التذاكر.',
      funnelSessions: 'جلسات',
      feedTitle: 'تغذية العمليات في الوقت الفعلي',
      feedSubtitle: 'سجلات مباشرة من عمليات بحث RAG والـ webhooks وبوابات الاتصال الهاتفي.',
    },
    wallboard: {
      consoleTitle: 'لوحة تحكم الاتصالات الهاتفية المباشرة',
      consoleSubtitle: 'تشغيل مكالمات صوتية واردة في الوقت الفعلي وإدارة تحويلات قائمة الانتظار لاختبار العمليات.',
      simulateCall: 'محاكاة مكالمة واردة',
      systemIdle: 'النظام في وضع الخمول. بانتظار النشاط...',
      kpiCallsInQueue: 'المكالمات في قائمة الانتظار',
      kpiCallsInQueueSub: 'المتصلون المنتظرون النشطون',
      kpiMaxWait: 'أقصى وقت انتظار',
      kpiMaxWaitSub: 'أطول مدة انتظار نشطة',
      kpiVoiceQuality: 'جودة الصوت (MOS)',
      kpiVoiceQualitySub: 'متوسط مؤشر الجودة (PCMU/Opus)',
      kpiActiveStaff: 'التوظيف النشط',
      kpiActiveStaffSub: 'إجمالي قائمة الوكلاء النشطين',
      queueTitle: 'قائمة انتظار الاتصالات الهاتفية المباشرة',
      queueSubtitle: 'المتصلون الواردون في الوقت الفعلي بانتظار تخصيص وكيل.',
      queueEmpty: 'لا يوجد متصلون في قائمة الانتظار حالياً.',
      queueColCustomer: 'اسم العميل',
      queueColPhone: 'رقم التواصل',
      queueColQueue: 'قائمة الانتظار المستهدفة',
      queueColPriority: 'الأولوية',
      queueColWait: 'وقت الانتظار',
      queueColAction: 'إجراء',
      routeAction: 'تحويل',
      sipTitle: 'جودة صوت Twilio وخطوط SIP',
      sipSubtitle: 'تشخيصات الإشارة في الوقت الفعلي، فقدان الحزم، وتدهور الترميز.',
      jitter: 'الاهتزاز',
      packetLoss: 'فقدان الحزم',
      supervisorTitle: 'مراقبة المشرف وسجل الهمس',
      supervisorSubtitle: 'تدقيق تفاعلات المشرف في الوقت الفعلي من الهمس والاقتحام والمراقبة الصامتة على قنوات الصوت النشطة.',
      supColSupervisor: 'اسم المشرف',
      supColAgent: 'الوكيل المستهدف',
      supColMode: 'وضع المراقبة',
      supColDuration: 'مدة النشاط',
      supColTimestamp: 'طابع وقت التشغيل',
      minsUnit: 'دقائق',
      actionWhisper: 'همس',
      actionBarge: 'اقتحام',
      actionSilent: 'مراقبة صامتة',
    },
    containment: {
      chartTitle: 'معدل احتواء دعم Farah AI (%)',
      guardrailTitle: 'حواجز الحماية التوليدية وسجلات الهلوسة',
      guardrailSubtitle: 'تنبيهات في الوقت الفعلي تتشغل بسبب إخفاقات التحقق الدلالي أو درجات الثقة المنخفضة.',
      confidenceScore: 'درجة الثقة',
      critical: 'حرج',
      escalatedTo: 'إلى الوكيل',
      promptMatrixTitle: 'مصفوفة أداء موجهات LLM',
      promptMatrixSubtitle: 'معاملات القياس لتكرارات الموجهات المنشورة عبر طبقات تصنيف Farah AI والاستدلال في SAP.',
      colPromptName: 'اسم تكوين الموجه',
      colCategory: 'طبقة الفئة',
      colSuccessRate: 'معدل نجاح الموجه',
      colAvgTokens: 'متوسط الرموز',
      colLatency: 'زمن الاستجابة (مللي ثانية)',
      tokensUnit: 'رموز',
    },
    costAnalytics: {
      kpiTotalCost: 'إجمالي تكلفة واجهة برمجة LLM',
      kpiTotalCostSub: 'مجمّع عبر نقاط نهاية LLM النشطة',
      kpiInputTokens: 'رموز الإدخال المستهلكة',
      kpiInputTokensSub: 'تحسين السياق المؤقت نشط',
      kpiOutputTokens: 'رموز الإخراج المولّدة',
      kpiOutputTokensSub: 'نسبة رموز الإكمال: 28.5%',
      chartTitle: 'تفصيل تكاليف نماذج الذكاء الاصطناعي (دولار)',
      logsTitle: 'سجلات مراقبة الرموز',
      inputLabel: 'إدخال',
      outputLabel: 'إخراج',
      ragTitle: 'تحليلات إخفاقات بحث Pinecone RAG',
      ragSubtitle: 'الاستعلامات التي نفّذها مستخدمو البوابة والتي فشلت في درجات التشابه أو عتبات المطابقة، مما يكشف ثغرات في توثيق قاعدة المعرفة.',
      colQuery: 'استعلام العميل غير المحلول',
      colCategory: 'فئة المقال',
      colFrequency: 'تنبيه التكرار',
      colClosestMatch: 'أقرب فهرس مطابق',
      hitsUnit: 'مرة',
      closestTarget: 'الأقرب:',
    },
    slaAnalytics: {
      kpiFirstResponse: 'SLA الاستجابة الأولى',
      kpiFirstResponseGoal: 'الهدف: 98.5% (ملتزم)',
      kpiResolution: 'SLA الحل',
      kpiResolutionGoal: 'الهدف: 98.0% (تحذير)',
      kpiAvgLatency: 'متوسط زمن الاستجابة',
      kpiAvgLatencySub: 'دون الهدف الأول للرد (5 دقائق)',
      csatTitle: 'تفصيل رضا العملاء (CSAT)',
      npsTitle: 'اتجاه مؤشر صافي الترويج (NPS)',
      escalationTitle: 'تدقيق تصعيدات الاتصالات والتذاكر',
      escalationSubtitle: 'سجل في الوقت الفعلي للحالات المُصعَّدة بسبب تراجع مشاعر العملاء أو أخطاء مزامنة API أو انتهاء وقت الجلسة المشتركة.',
      colTicketId: 'رقم التذكرة',
      colCustomer: 'العميل',
      colPriority: 'الأولوية',
      colReason: 'سبب التصعيد',
      colTime: 'وقت التصعيد',
      minsAgo: 'دقائق مضت',
    }
  }
} as const;
"""
    
    with open(ar_path, 'w', encoding='utf-8') as f:
        f.write(base_ar + new_portal_namespaces)
    print("ar.ts updated successfully!")
else:
    print("Could not find myTickets block to insert translations.")
