'use client';

import React from 'react';
import { Sparkles, ChevronRight, Clock, ThumbsUp, ArrowRight } from 'lucide-react';
import { INTERACTIVE_CARD, SURFACE_WORKSPACE } from '@/design-system/tokens';

interface Article {
  id: string;
  title: string;
  category: string;
  content: string;
  helpfulCount: number;
  tags: string[];
}

interface RelatedArticlesProps {
  currentArticleId: string;
  articles: Article[];
  onSelect: (id: string) => void;
  isRtl?: boolean;
}

const CATEGORY_COLORS: Record<string, { bg: string; text: string }> = {
  'Returns & Refunds': { bg: 'bg-amber-500/10', text: 'text-amber-600 dark:text-amber-400' },
  'Developer APIs': { bg: 'bg-violet-500/10', text: 'text-violet-600 dark:text-violet-400' },
  'Account & Access': { bg: 'bg-emerald-500/10', text: 'text-emerald-600 dark:text-emerald-400' },
};
const DEFAULT_COLOR = { bg: 'bg-blue-500/10', text: 'text-blue-600 dark:text-blue-400' };

const READ_TIMES = ['2 min', '3 min', '4 min', '5 min'];

export function RelatedArticles({
  currentArticleId,
  articles,
  onSelect,
  isRtl = false
}: RelatedArticlesProps) {
  const related = articles.filter((a) => a.id !== currentArticleId).slice(0, 4);

  if (related.length === 0) return null;

  return (
    <div
      className={`rounded-3xl p-5 space-y-4 border ${SURFACE_WORKSPACE}`}
      dir={isRtl ? 'rtl' : 'ltr'}
    >
      {/* Header */}
      <div className="flex items-center gap-2.5 pb-3 border-b border-slate-200 dark:border-slate-800">
        <div className="p-1.5 bg-violet-500/10 text-violet-500 rounded-lg shrink-0">
          <Sparkles className="w-3.5 h-3.5" />
        </div>
        <div>
          <h4 className="font-extrabold text-xs text-slate-900 dark:text-white leading-tight">
            {isRtl ? 'مقترحات الذكاء الاصطناعي' : 'AI-Recommended'}
          </h4>
          <span className="text-[9px] text-slate-400 font-semibold block mt-0.5">
            {isRtl ? 'مقالات ذات صلة' : 'Related articles'}
          </span>
        </div>
      </div>

      {/* Article list */}
      <div className="space-y-2.5">
        {related.map((art, idx) => {
          const colors = CATEGORY_COLORS[art.category] ?? DEFAULT_COLOR;
          const readTime = READ_TIMES[idx % READ_TIMES.length];

          return (
            <button
              key={art.id}
              type="button"
              onClick={() => onSelect(art.id)}
              className={`w-full text-start group p-3.5 bg-white dark:bg-slate-950 rounded-2xl cursor-pointer space-y-2 ${INTERACTIVE_CARD}`}
            >
              {/* Rank + Category */}
              <div className="flex items-center justify-between gap-2">
                <span className={`px-2 py-0.5 rounded-md text-[9px] font-bold uppercase font-mono ${colors.bg} ${colors.text}`}>
                  {art.category}
                </span>
                <span className="text-[9px] text-slate-400 font-mono font-bold">
                  #{idx + 1}
                </span>
              </div>

              {/* Title */}
              <h5 className="font-bold text-xs text-slate-800 dark:text-white line-clamp-2 leading-snug group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors duration-150">
                {art.title}
              </h5>

              {/* Snippet */}
              <p className="text-[10px] text-slate-450 dark:text-slate-400 line-clamp-2 leading-relaxed font-normal">
                {art.content.slice(0, 100)}…
              </p>

              {/* Footer meta */}
              <div className="flex items-center justify-between pt-0.5">
                <span className="flex items-center gap-1 text-[9px] text-slate-400 font-bold font-mono">
                  <ThumbsUp className="w-2.5 h-2.5" />
                  {art.helpfulCount}
                </span>
                <span className="flex items-center gap-1 text-[9px] text-slate-400 font-mono">
                  <Clock className="w-2.5 h-2.5" />
                  {isRtl ? `${readTime} قراءة` : `${readTime} read`}
                </span>
                <ArrowRight
                  className={`w-3 h-3 text-blue-400 opacity-0 group-hover:opacity-100 transition-opacity duration-150 ${isRtl ? 'rotate-180' : ''}`}
                />
              </div>
            </button>
          );
        })}
      </div>

      {/* AI note */}
      <div className="pt-1 border-t border-slate-200 dark:border-slate-800/60">
        <p className="text-[9px] text-slate-400 dark:text-slate-500 leading-relaxed">
          {isRtl
            ? '⚡ مقترحات تُولَّد بواسطة نموذج RAG الدلالي بناءً على سياق المقال.'
            : '⚡ Suggestions generated by semantic RAG model based on current article context.'}
        </p>
      </div>
    </div>
  );
}

export default RelatedArticles;
