import { AuditEvent, CompliancePolicy } from '@/types/audit';

export const mockAuditEvents: AuditEvent[] = [
  {
    id: 'evt-2026-1024',
    timestamp: '2026-06-03T20:15:32Z',
    actor: 'Liam Bennett',
    actorRole: 'Security Administrator',
    actionType: 'Credential Rotation',
    targetResource: 'Twilio Gateway Credentials',
    severity: 'high',
    tenantId: 'tenant-dubai-tel',
    tenantName: 'Dubai Telecom',
    status: 'open',
    details: 'Rotated secondary API auth token for the Twilio provider account. Verified active routing handshake with no session dropouts.',
    ipAddress: '192.168.1.14',
    complianceImpact: 'HIPAA & PCI-DSS Section 8.3: Frequent secret key updates enforced.'
  },
  {
    id: 'evt-2026-1025',
    timestamp: '2026-06-03T19:42:10Z',
    actor: 'Farah Al-Mutawa',
    actorRole: 'Tenant Operator',
    actionType: 'Safety Limit Slide Update',
    targetResource: 'Toxicity Sensitivity Score',
    severity: 'critical',
    tenantId: 'tenant-riyadh-fin',
    tenantName: 'Riyadh Financial',
    status: 'escalated',
    details: 'Reduced Toxicity Sensitivity threshold from 0.85 to 0.40. System flagged action due to potential safety policy violations.',
    ipAddress: '10.244.32.19',
    complianceImpact: 'Safety Regulations Policy compliance: Score dropped below recommended compliance limit (0.70).'
  },
  {
    id: 'evt-2026-1026',
    timestamp: '2026-06-03T18:05:44Z',
    actor: 'System Admin Daemon',
    actorRole: 'System Automation',
    actionType: 'Vector Compaction Triggered',
    targetResource: 'Pinecone Ingestion Index',
    severity: 'low',
    tenantId: 'tenant-cairo-nb',
    tenantName: 'Cairo National Bank',
    status: 'reviewed',
    details: 'Automated partition compaction completed. Wiped 1,240 inactive vector indices to free allocated memory footprint.',
    ipAddress: '127.0.0.1',
    complianceImpact: 'Data Compaction Policy compliance.'
  },
  {
    id: 'evt-2026-1027',
    timestamp: '2026-06-03T16:50:00Z',
    actor: 'Amir Mansour',
    actorRole: 'Billing Auditor',
    actionType: 'Tenant Suspension',
    targetResource: 'Billing Invoice Overdue',
    severity: 'high',
    tenantId: 'tenant-cairo-nb',
    tenantName: 'Cairo National Bank',
    status: 'open',
    details: 'Suspended billing account for Cairo National Bank after repeated overdue invoice notifications (Billing Ref. CNB-902).',
    ipAddress: '192.168.4.25',
    complianceImpact: 'SLA Breach Auto-Escalation compliance.'
  },
  {
    id: 'evt-2026-1028',
    timestamp: '2026-06-03T15:22:18Z',
    actor: 'Liam Bennett',
    actorRole: 'Security Administrator',
    actionType: 'Guardrail Override Attempt',
    targetResource: 'PII Masking Ingestion Rule',
    severity: 'critical',
    tenantId: 'global-platform',
    tenantName: 'Global Platform Admin',
    status: 'open',
    details: 'Attempted to bypass strict SSN masking rules on the Arabic RAG knowledge document crawler pipeline.',
    ipAddress: '192.168.1.14',
    complianceImpact: 'GDPR Article 32: Unencrypted raw personal records transmission blockage triggered.'
  },
  {
    id: 'evt-2026-1029',
    timestamp: '2026-06-03T14:10:05Z',
    actor: 'Sarah Jenkins',
    actorRole: 'Omnichannel Lead',
    actionType: 'Channel Created',
    targetResource: 'WhatsApp Template Sync',
    severity: 'medium',
    tenantId: 'tenant-dubai-tel',
    tenantName: 'Dubai Telecom',
    status: 'reviewed',
    details: 'Registered WhatsApp business support channel template: "order_exemption_notification". Approved by Meta Business API.',
    ipAddress: '82.44.192.8',
    complianceImpact: 'Omnichannel safety governance.'
  },
  {
    id: 'evt-2026-1030',
    timestamp: '2026-06-03T11:30:40Z',
    actor: 'System Admin Daemon',
    actorRole: 'System Automation',
    actionType: 'API Gateway Sync',
    targetResource: 'Speech Providers Credentials',
    severity: 'medium',
    tenantId: 'global-platform',
    tenantName: 'Global Platform Admin',
    status: 'archived',
    details: 'Synced API gateway encryption keys with Speech Provider endpoints (Farah AI latency indexing daemon).',
    ipAddress: '127.0.0.1',
    complianceImpact: 'ASR/TTS Speech Latency Audit Compliance.'
  },
  {
    id: 'evt-2026-1031',
    timestamp: '2026-06-03T09:15:22Z',
    actor: 'Farah Al-Mutawa',
    actorRole: 'Tenant Operator',
    actionType: 'NLU Rollout Split Change',
    targetResource: 'A/B Traffic split configuration',
    severity: 'medium',
    tenantId: 'tenant-riyadh-fin',
    tenantName: 'Riyadh Financial',
    status: 'reviewed',
    details: 'Split active user traffic splits for NLU: Version 3.4.1 allocated 70% split, version 3.4.2 allocated 30% split.',
    ipAddress: '10.244.32.19',
    complianceImpact: 'NLU Traffic Governance Audit.'
  },
  {
    id: 'evt-2026-1032',
    timestamp: '2026-06-03T08:00:11Z',
    actor: 'Amir Mansour',
    actorRole: 'Billing Auditor',
    actionType: 'LLM Registry Model Added',
    targetResource: 'Gemini 1.5 Pro registry tier',
    severity: 'low',
    tenantId: 'global-platform',
    tenantName: 'Global Platform Admin',
    status: 'reviewed',
    details: 'Added active foundation model Gemini 1.5 Pro to the model directory registry with 400ms search loader validation parameters.',
    ipAddress: '192.168.4.25',
    complianceImpact: 'Model Registry Licensing compliance.'
  },
  {
    id: 'evt-2026-1033',
    timestamp: '2026-06-03T07:12:00Z',
    actor: 'Liam Bennett',
    actorRole: 'Security Administrator',
    actionType: 'SIP Trunk Deactivation',
    targetResource: 'SIP Trunk Cairo_VOIP_01',
    severity: 'high',
    tenantId: 'tenant-cairo-nb',
    tenantName: 'Cairo National Bank',
    status: 'open',
    details: 'Manually deactivated SIP trunk trunk-cairo-01 due to connection failures breaching MOS voice quality levels (MOS below 2.0).',
    ipAddress: '192.168.1.14',
    complianceImpact: 'SLA Availability Policy compliance.'
  }
];

export const mockCompliancePolicies: CompliancePolicy[] = [
  {
    id: 'pol-001',
    name: 'MFA Enforcement for Client Admin',
    category: 'Access Control',
    status: 'enabled',
    lastUpdated: '2026-05-15',
    assignedScope: 'Client Admin Portal Login',
    complianceState: 'compliant',
    description: 'Enforce multi-factor verification prompts via SMS or OTP challenge scripts for all client admin login routes.'
  },
  {
    id: 'pol-002',
    name: 'PII Masking on Knowledge Ingestion',
    category: 'Ingestion Pipeline',
    status: 'enabled',
    lastUpdated: '2026-06-01',
    assignedScope: 'Vector DB Indexes & Crawler',
    complianceState: 'compliant',
    description: 'Automatically mask Social Security Numbers, Credit Cards, and passwords from ingested document text segments.'
  },
  {
    id: 'pol-003',
    name: 'Toxicity Score Safety Threshold',
    category: 'Omnichannel Safety',
    status: 'enabled',
    lastUpdated: '2026-05-28',
    assignedScope: 'Global Chatbot Handler',
    complianceState: 'warning',
    description: 'Reject chatbot generation and redirect the conversation if Toxicity Sensitivity scores drop below 0.70.'
  },
  {
    id: 'pol-004',
    name: 'SLA Breach Auto-Escalation',
    category: 'Billing & SLA',
    status: 'enabled',
    lastUpdated: '2026-04-12',
    assignedScope: 'Unified Support Inbox queues',
    complianceState: 'violated',
    description: 'Escalate conversation to Supervisor Whisper status automatically when response SLA exceeds 15 minutes.'
  },
  {
    id: 'pol-005',
    name: 'SIP Concurrency Limit Cap',
    category: 'Omnichannel Safety',
    status: 'disabled',
    lastUpdated: '2026-05-10',
    assignedScope: 'SIP Trunk Concurrency',
    complianceState: 'disabled',
    description: 'Deactivate outbound channels automatically if tenant concurrent lines exceed the contract license limits.'
  },
  {
    id: 'pol-006',
    name: 'Session Timeout Policy',
    category: 'Access Control',
    status: 'enabled',
    lastUpdated: '2026-06-02',
    assignedScope: 'Agent Workspace dashboard',
    complianceState: 'compliant',
    description: 'Terminate active browser sessions and lock screens after 15 minutes of operator session inactivity.'
  },
  {
    id: 'pol-007',
    name: 'WhatsApp Template Pre-Approval Check',
    category: 'Omnichannel Safety',
    status: 'enabled',
    lastUpdated: '2026-05-20',
    assignedScope: 'WhatsApp Channels API',
    complianceState: 'compliant',
    description: 'Restrict outbound notification delivery to Meta-approved message template brackets.'
  }
];
