'use client';

import React, { useState, useMemo } from 'react';
import { 
  CreditCard, 
  Sparkles, 
  Receipt, 
  HardDrive, 
  BarChart2, 
  ShieldCheck, 
  ArrowUpRight, 
  TrendingUp, 
  Info, 
  HelpCircle, 
  Download, 
  Check, 
  ShieldAlert, 
  Cpu, 
  Layers, 
  User, 
  Settings, 
  ArrowRight, 
  X, 
  AlertTriangle, 
  Coins, 
  RefreshCw,
  Phone,
  MessageSquare
} from 'lucide-react';
import { useApp } from '@/context/AppContext';
import { useNotificationStore } from '@/stores/notifications/notificationStore';
import { usePermission } from '@/stores/permissionStore';

// Local Translation dictionary for premium Arabic and English SaaS support
interface LocalDict {
  billingTitle: string;
  billingSubtitle: string;
  failedAlertTitle: string;
  failedAlertDesc: string;
  failedAlertBtn: string;
  activePlanBadge: string;
  activePlanDesc: string;
  nextRenewal: string;
  btnManageSub: string;
  resourceUsageTitle: string;
  resourceUsageSubtitle: string;
  invoiceTableTitle: string;
  invoiceColRef: string;
  invoiceColPeriod: string;
  invoiceColAmount: string;
  invoiceColStatus: string;
  invoiceColActions: string;
  btnDownload: string;
  btnView: string;
  paymentTitle: string;
  paymentSubtitle: string;
  cardExpiry: string;
  cardHolder: string;
  billingEmailTitle: string;
  vatIdLabel: string;
  billingAddressLabel: string;
  btnEditBilling: string;
  optTitle: string;
  optSubtitle: string;
  optEstimatedSavings: string;
  btnApplyOpt: string;
  btnAppliedOpt: string;
  limitComputeTitle: string;
  limitComputeSubtitle: string;
  limitVectorTitle: string;
  limitVectorSubtitle: string;
  limitSeatsTitle: string;
  limitSeatsSubtitle: string;
  limitRateTitle: string;
  limitRateSubtitle: string;
  overageAlert: string;
  exhaustionProjected: string;
  modalCompareTitle: string;
  modalCompareSubtitle: string;
  modalClose: string;
  planFree: string;
  planStarter: string;
  planGrowth: string;
  planEnterprise: string;
  planEnterprisePlus: string;
  btnSwitchPlan: string;
  btnActivePlan: string;
  featureMatrixTitle: string;
  invoicePreviewTitle: string;
  invoicePreviewDesc: string;
}

const enLocal: LocalDict = {
  billingTitle: 'Billing & Subscription Operations Center',
  billingSubtitle: 'Telemetry and management of SaaS subscriptions, AI resource quotas, and financial transactions.',
  failedAlertTitle: 'Payment Processing Action Required',
  failedAlertDesc: 'We were unable to charge your Mastercard ending in 8842 for invoice INV-2026-001 ($1,250.00). Please update payment credentials to avoid service disruption.',
  failedAlertBtn: 'Update Card Details',
  activePlanBadge: 'Active Plan',
  activePlanDesc: 'Fully custom SLA suite with high-throughput speech pipelines.',
  nextRenewal: 'Next Renewal:',
  btnManageSub: 'Compare Subscription Tiers',
  resourceUsageTitle: 'AI Resource Utilization Telemetry',
  resourceUsageSubtitle: 'Live tracking of platform compute and API routing volume counts.',
  invoiceTableTitle: 'Invoice Ledger & Historical Logs',
  invoiceColRef: 'Invoice Reference',
  invoiceColPeriod: 'Billing Period',
  invoiceColAmount: 'Billed Amount',
  invoiceColStatus: 'Status',
  invoiceColActions: 'Actions',
  btnDownload: 'Download PDF',
  btnView: 'View Details',
  paymentTitle: 'Primary Payment Instrument',
  paymentSubtitle: 'Default credential used for automated platform subscription billing.',
  cardExpiry: 'Expires',
  cardHolder: 'Cardholder',
  billingEmailTitle: 'Billing Contact Registry',
  vatIdLabel: 'VAT/Tax ID',
  billingAddressLabel: 'Billing Address',
  btnEditBilling: 'Edit Contact Details',
  optTitle: 'Farah AI Cost Optimization Engine',
  optSubtitle: 'Proactive recommendations generated by operational analysis of tenant idling assets.',
  optEstimatedSavings: 'Monthly Savings:',
  btnApplyOpt: 'Apply Savings',
  btnAppliedOpt: 'Optimization Applied',
  limitComputeTitle: 'Vector database Capacity',
  limitComputeSubtitle: 'Pinecone shard database capacity bounds.',
  limitVectorTitle: 'LLM Token Volumetrics',
  limitVectorSubtitle: 'Total cumulative token API payload size.',
  limitSeatsTitle: 'Workspace Roster Occupancy',
  limitSeatsSubtitle: 'Active platform seats assigned to human roster.',
  limitRateTitle: 'ASR/TTS Speech Gateway Minutes',
  limitRateSubtitle: 'Real-time text-to-speech audio gateway minutes.',
  overageAlert: 'Approaching limit boundary threshold. Potential overages will apply.',
  exhaustionProjected: 'Projected limit exhaustion:',
  modalCompareTitle: 'SaaS Subscription Plan Matrix',
  modalCompareSubtitle: 'Compare system capacity bounds and features across standard tiers.',
  modalClose: 'Close Panel',
  planFree: 'Starter',
  planStarter: 'Starter',
  planGrowth: 'Growth Tier',
  planEnterprise: 'Enterprise Pro',
  planEnterprisePlus: 'AI Enterprise Plus',
  btnSwitchPlan: 'Switch to Plan',
  btnActivePlan: 'Active Tier',
  featureMatrixTitle: 'Feature Entitlement Matrix',
  invoicePreviewTitle: 'Invoice Overview',
  invoicePreviewDesc: 'Itemized operational billing statement for billing cycle.'
};

const arLocal: LocalDict = {
  billingTitle: 'مركز عمليات الفوترة والاشتراكات',
  billingSubtitle: 'مراقبة وإدارة اشتراكات SaaS، وحصص موارد الذكاء الاصطناعي، والمعاملات المالية.',
  failedAlertTitle: 'مطلوب اتخاذ إجراء بشأن الدفع',
  failedAlertDesc: 'تعذر تحصيل رسوم بطاقة Mastercard المنتهية بـ 8842 للفاتورة INV-2026-001 بقيمة $1,250.00. يرجى تحديث تفاصيل الدفع لتجنب انقطاع الخدمة.',
  failedAlertBtn: 'تحديث بيانات البطاقة',
  activePlanBadge: 'الخطة النشطة',
  activePlanDesc: 'اتفاقية مستوى خدمة مخصصة بالكامل مع تدفقات معالجة كلامية عالية السعة.',
  nextRenewal: 'التجديد القادم:',
  btnManageSub: 'مقارنة فئات الاشتراكات',
  resourceUsageTitle: 'بيانات قياس استخدام الموارد',
  resourceUsageSubtitle: 'متابعة مباشرة لعمليات الحوسبة وحجم استخدام واجهة برمجة التطبيقات (API).',
  invoiceTableTitle: 'سجل الفواتير والمعاملات التاريخية',
  invoiceColRef: 'مرجع الفاتورة',
  invoiceColPeriod: 'فترة الفوترة',
  invoiceColAmount: 'القيمة الإجمالية',
  invoiceColStatus: 'الحالة',
  invoiceColActions: 'الإجراءات',
  btnDownload: 'تحميل PDF',
  btnView: 'عرض التفاصيل',
  paymentTitle: 'وسيلة الدفع الرئيسية',
  paymentSubtitle: 'البطاقة الافتراضية المستخدمة في عمليات الفوترة التلقائية للاشتراك.',
  cardExpiry: 'ينتهي في',
  cardHolder: 'حامل البطاقة',
  billingEmailTitle: 'سجل جهات اتصال الفوترة',
  vatIdLabel: 'الرقم الضريبي VAT',
  billingAddressLabel: 'عنوان الفوترة',
  btnEditBilling: 'تعديل جهات الاتصال',
  optTitle: 'محرك فرح للذكاء الاصطناعي لتقليل التكاليف',
  optSubtitle: 'توصيات استباقية تم إنشاؤها عبر تحليل استهلاك موارد المستأجر.',
  optEstimatedSavings: 'التوفير الشهري:',
  btnApplyOpt: 'تطبيق التوفير',
  btnAppliedOpt: 'تم تطبيق خفض التكلفة',
  limitComputeTitle: 'سعة قاعدة البيانات المتجهة',
  limitComputeSubtitle: 'سعة تخزين متجهات Pinecone المتاحة.',
  limitVectorTitle: 'استهلاك الرموز (LLM Tokens)',
  limitVectorSubtitle: 'إجمالي حجم استهلاك رموز واجهة البرمجة.',
  limitSeatsTitle: 'إشغال مقاعد مساحة العمل',
  limitSeatsSubtitle: 'المقاعد النشطة المخصصة للموظفين البشريين.',
  limitRateTitle: 'دقائق بوابة تحويل الصوت (ASR/TTS)',
  limitRateSubtitle: 'دقائق الاتصال الصوتي عبر بوابة تحويل الصوت والترجمة.',
  overageAlert: 'تقترب من الحد الأقصى للموارد. قد تطبق رسوم إضافية.',
  exhaustionProjected: 'تاريخ الاستهلاك المتوقع:',
  modalCompareTitle: 'مصفوفة خطط الاشتراكات',
  modalCompareSubtitle: 'قارن بين حدود قدرات النظام والميزات عبر الفئات القياسية.',
  modalClose: 'إغلاق اللوحة',
  planFree: 'الباقة الأساسية',
  planStarter: 'الباقة الأساسية',
  planGrowth: 'باقة النمو',
  planEnterprise: 'المؤسسات الاحترافية',
  planEnterprisePlus: 'باقة الذكاء الاصطناعي الفائقة',
  btnSwitchPlan: 'التبديل إلى الخطة',
  btnActivePlan: 'الخطة النشطة حالياً',
  featureMatrixTitle: 'مصفوفة استحقاقات الميزات',
  invoicePreviewTitle: 'معاينة الفاتورة',
  invoicePreviewDesc: 'بيان فوترة تشغيلي مفصل لدورة الفوترة المحددة.'
};

export function BillingTab() {
  const { lang, addAuditLog } = useApp();
  const isRtl = lang === 'ar';
  const loc = isRtl ? arLocal : enLocal;
  const { canEdit, canManage, canExport } = usePermission('billing');

  // 1. Subscription & Plan States
  const [activePlan, setActivePlan] = useState<'starter' | 'growth' | 'enterprise' | 'ai_plus'>('enterprise');
  
  // 2. Optimization States
  const [appliedOpts, setAppliedOpts] = useState<string[]>([]);
  const [totalSavings, setTotalSavings] = useState(0);

  // 3. Modals state
  const [showCompareModal, setShowCompareModal] = useState(false);
  const [selectedInvoice, setSelectedInvoice] = useState<any | null>(null);
  const [showEditModal, setShowEditModal] = useState(false);

  // 4. Contact & Payment Info States
  const [paymentCard, setPaymentCard] = useState({
    brand: 'Mastercard',
    last4: '8842',
    expiry: '09/29',
    holder: 'ACME CORP MIDDLE EAST'
  });
  
  const [billingEmails, setBillingEmails] = useState(['procurement@acme.com', 'finance-billing@acme.com']);
  const [vatId, setVatId] = useState('SA-994827103');
  const [billingAddress, setBillingAddress] = useState({
    line1: '100 King Fahd Road, Suite 402',
    city: 'Riyadh',
    postalCode: '11564',
    country: 'Saudi Arabia'
  });

  // Temporary Edit Form state
  const [editEmailsText, setEditEmailsText] = useState('');
  const [editCardLast4, setEditCardLast4] = useState('');
  const [editAddressLine, setEditAddressLine] = useState('');

  // 5. Invoices lists
  const invoices = useMemo(() => [
    { id: 'INV-2026-004', period: 'May 01 - May 31, 2026', amount: activePlan === 'enterprise' ? '$1,499.00' : activePlan === 'growth' ? '$199.00' : activePlan === 'starter' ? '$49.00' : '$4,999.00', status: 'paid', date: '2026-05-31', method: `${paymentCard.brand} ending in ${paymentCard.last4}` },
    { id: 'INV-2026-003', period: 'Apr 01 - Apr 30, 2026', amount: '$1,499.00', status: 'paid', date: '2026-04-30', method: 'Mastercard ending in 8842' },
    { id: 'INV-2026-002', period: 'Mar 01 - Mar 31, 2026', amount: '$1,250.00', status: 'paid', date: '2026-03-31', method: 'Mastercard ending in 8842' },
    { id: 'INV-2026-001', period: 'Feb 01 - Feb 28, 2026', amount: '$1,250.00', status: 'failed', date: '2026-02-28', method: 'Mastercard ending in 8842' }
  ], [activePlan, paymentCard]);

  const [invoiceFilter, setInvoiceFilter] = useState<'all' | 'paid' | 'failed'>('all');

  const filteredInvoices = useMemo(() => {
    return invoices.filter(inv => {
      if (invoiceFilter === 'paid') return inv.status === 'paid';
      if (invoiceFilter === 'failed') return inv.status === 'failed';
      return true;
    });
  }, [invoices, invoiceFilter]);

  // Plan limits map
  const planLimits = {
    starter: { name: loc.planStarter, basePrice: 49, tokenLimit: '1,000,000', voiceLimit: '500', seatLimit: 5, vectorLimit: '10,000' },
    growth: { name: loc.planGrowth, basePrice: 199, tokenLimit: '5,000,000', voiceLimit: '2,000', seatLimit: 15, vectorLimit: '50,000' },
    enterprise: { name: loc.planEnterprise, basePrice: 1499, tokenLimit: '10,000,000', voiceLimit: '5,000', seatLimit: 50, vectorLimit: '100,000' },
    ai_plus: { name: loc.planEnterprisePlus, basePrice: 4999, tokenLimit: '50,000,000', voiceLimit: '25,000', seatLimit: 150, vectorLimit: '500,000' }
  };

  const activePlanDetails = planLimits[activePlan];
  const activePriceAdjusted = Math.max(0, activePlanDetails.basePrice - totalSavings);

  // Optimizations list
  const optimizationList = [
    { id: 'opt-unused-seats', savings: 180, titleEn: 'Deallocate 12 idle workspace agent seats', titleAr: 'إلغاء تخصيص 12 مقعد للوكلاء غير النشطين', category: 'workforce', descriptionEn: '12 active agent seats have not recorded telephony or conversation logs in 30 days.', descriptionAr: 'لم تسجل 12 من مقاعد الوكلاء النشطة أي حركة اتصال أو محادثات طوال 30 يوماً.' },
    { id: 'opt-stale-vectors', savings: 120, titleEn: 'Archive 25,000 stale RAG knowledge base vectors', titleAr: 'أرشفة 25,000 متجه معرفة قديم من RAG', category: 'storage', descriptionEn: 'Knowledge base synchronization sources have deprecated pages that consume DB shards.', descriptionAr: 'مصادر المعرفة تحتوي على صفحات ملغاة تستهلك خلايا قاعدة البيانات بدون استخدام.' },
    { id: 'opt-routing-flash', savings: 350, titleEn: 'Switch low-priority classification to Gemini Flash', titleAr: 'تحويل تصنيف الحالات البسيطة إلى Gemini Flash', category: 'compute', descriptionEn: 'Automated triage queries currently routed to high-cost LLM pipelines can be offloaded.', descriptionAr: 'يمكن تخفيف العبء بتحويل استفسارات التصنيف البسيطة الموجهة حالياً لنماذج مكلفة.' },
    { id: 'opt-log-cleanup', savings: 50, titleEn: 'Compress web chat logs older than 180 days', titleAr: 'ضغط سجلات دردشة الويب الأقدم من 180 يوماً', category: 'storage', descriptionEn: 'Release redundant database index partitions and keep aggregate telemetry only.', descriptionAr: 'تحرير مساحة قاعدة البيانات المخصصة للسجلات القديمة والاحتفاظ بالتقارير المجمعة فقط.' }
  ];

  // Apply Optimization Action
  const handleApplyOpt = (id: string, savings: number, title: string) => {
    if (!canEdit) return;
    if (appliedOpts.includes(id)) return;
    
    setAppliedOpts(prev => [...prev, id]);
    setTotalSavings(prev => prev + savings);

    // Write toast via notificationStore
    useNotificationStore.getState().addAlert({
      category: 'operations',
      source: 'operations',
      severity: 'success',
      alertCode: 'BILLING_OPTIMIZATION_APPLIED',
      sourceEntity: 'Farah AI Engine',
      title: isRtl ? 'تم تطبيق خفض التكلفة' : 'Optimization Applied',
      message: isRtl 
        ? `تم تطبيق خفض التكلفة "${title}". تم توفير $${savings}/شهرياً في الاشتراك الفعلي.` 
        : `AI Cost Optimization "${title}" applied successfully. Saved $${savings}/mo.`,
      metadata: {
        sourceSystem: 'Farah AI Operations',
        savingsAmount: `$${savings}`
      }
    });

    addAuditLog(`Applied cost optimization: ${title} (Saved $${savings}/month)`, 'success');
  };

  // Switch subscription tier
  const handleSwitchPlan = (tier: 'starter' | 'growth' | 'enterprise' | 'ai_plus') => {
    if (!canManage) return;
    setActivePlan(tier);
    setShowCompareModal(false);

    useNotificationStore.getState().addAlert({
      category: 'operations',
      source: 'operations',
      severity: 'info',
      alertCode: 'SUBSCRIPTION_TIER_CHANGED',
      sourceEntity: 'Procurement Billing Portal',
      title: isRtl ? 'تم تعديل فئة الاشتراك' : 'Subscription Tier Modified',
      message: isRtl 
        ? `تم تبديل باقة النظام بنجاح إلى "${planLimits[tier].name}". يتم تحديث حدود الموارد فوراً.` 
        : `Subscription successfully updated to ${planLimits[tier].name}. Allocations revised.`,
      metadata: {
        tierName: tier,
        monthlyBase: `$${planLimits[tier].basePrice}`
      }
    });

    addAuditLog(`Updated tenant subscription plan to ${planLimits[tier].name}`, 'success');
  };

  // Open Edit billing details
  const handleOpenEditModal = () => {
    if (!canEdit) return;
    setEditEmailsText(billingEmails.join(', '));
    setEditCardLast4(paymentCard.last4);
    setEditAddressLine(billingAddress.line1);
    setShowEditModal(true);
  };

  // Save billing details
  const handleSaveBilling = (e: React.FormEvent) => {
    e.preventDefault();
    if (!canEdit) return;

    const emailsArray = editEmailsText.split(',').map(em => em.trim()).filter(Boolean);
    if (emailsArray.length > 0) setBillingEmails(emailsArray);

    if (editCardLast4.length === 4 && /^\d+$/.test(editCardLast4)) {
      setPaymentCard(prev => ({ ...prev, last4: editCardLast4 }));
    }

    if (editAddressLine.trim().length > 5) {
      setBillingAddress(prev => ({ ...prev, line1: editAddressLine.trim() }));
    }

    setShowEditModal(false);

    useNotificationStore.getState().addAlert({
      category: 'operations',
      source: 'operations',
      severity: 'success',
      alertCode: 'BILLING_CONTACTS_UPDATED',
      sourceEntity: 'Billing Controller',
      title: isRtl ? 'تم تحديث بيانات الاتصال والدفع' : 'Billing Information Updated',
      message: isRtl 
        ? 'تم حفظ تفاصيل الدفع والعناوين بنجاح في سجلات المستأجر.' 
        : 'Billing payment parameters and contacts have been successfully updated.',
      metadata: {
        sourceSystem: 'Billing Settings Panel'
      }
    });

    addAuditLog('Updated tenant billing contact and card parameters', 'success');
  };

  // Download PDF simulated
  const handleDownloadPdf = (invId: string) => {
    useNotificationStore.getState().addAlert({
      category: 'operations',
      source: 'operations',
      severity: 'info',
      alertCode: 'INVOICE_PDF_DOWNLOAD',
      sourceEntity: 'Invoice Ledger',
      title: isRtl ? 'تحميل الفاتورة PDF' : 'Downloading Invoice PDF',
      message: isRtl 
        ? `بدأ تحميل الفاتورة ${invId}.pdf... يرجى مراجعة نافذة التحميل بالمتصفح.` 
        : `Generating PDF for ${invId}. Download started.`,
      metadata: {
        invoiceId: invId
      }
    });

    addAuditLog(`Generated PDF download trigger for ${invId}`, 'success');
  };

  // SVG Line Chart coordinates calculations (last 7 days of API usage)
  const chartData = [12.4, 15.2, 11.8, 18.9, 22.1, 14.5, 19.3];
  const chartDays = isRtl 
    ? ['الأحد', 'السبت', 'الجمعة', 'الخميس', 'الأربعاء', 'الثلاثاء', 'الإثنين']
    : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

  return (
    <div className="space-y-6 max-w-7xl mx-auto px-1" dir={isRtl ? 'rtl' : 'ltr'}>
      {/* ─── Header ─── */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-100 dark:border-slate-850 pb-5">
        <div className="space-y-1">
          <h2 className="text-lg font-black text-slate-900 dark:text-white leading-none">
            {loc.billingTitle}
          </h2>
          <p className="text-xs text-slate-500 dark:text-slate-400">
            {loc.billingSubtitle}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <span className="px-2.5 py-1 bg-emerald-100 dark:bg-emerald-950/20 text-emerald-700 dark:text-emerald-400 text-[10px] font-bold tracking-wider rounded-lg uppercase font-mono">
            Tenant: MP-ACME-PRODUCTION
          </span>
        </div>
      </div>

      {/* ─── Unpaid Failed Payment Banner ─── */}
      {invoices.some(inv => inv.status === 'failed') && (
        <div className="bg-red-500/10 border border-red-500/20 dark:border-red-500/30 rounded-3xl p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-4 animate-in fade-in-50 slide-in-from-top-4">
          <div className="flex items-start sm:items-center gap-3.5">
            <div className="w-10 h-10 rounded-2xl bg-red-500/20 text-red-600 dark:text-red-400 flex items-center justify-center shrink-0">
              <ShieldAlert className="w-5 h-5" />
            </div>
            <div className="space-y-0.5">
              <h4 className="font-bold text-xs text-red-950 dark:text-red-400 uppercase tracking-wider font-mono">
                {loc.failedAlertTitle}
              </h4>
              <p className="text-[11px] text-red-800 dark:text-red-400/80 leading-relaxed font-semibold">
                {loc.failedAlertDesc}
              </p>
            </div>
          </div>
          <button 
            onClick={handleOpenEditModal}
            disabled={!canEdit}
            className={`px-4 py-2.5 text-white font-bold rounded-2xl text-[10.5px] uppercase tracking-wider transition-all whitespace-nowrap ${
              !canEdit 
                ? 'bg-red-400 opacity-60 cursor-not-allowed' 
                : 'bg-red-600 hover:bg-red-700 active:scale-95 cursor-pointer'
            }`}
            title={!canEdit ? "Requires Edit Permission" : undefined}
          >
            {loc.failedAlertBtn}
          </button>
        </div>
      )}

      {/* ─── Subscription Overview Header (Section 1) ─── */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Card 1: Subscription Tier */}
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-5 shadow-xs relative overflow-hidden flex flex-col justify-between h-36 group hover:border-blue-500/30 transition-all">
          <div className="flex justify-between items-start">
            <div className="space-y-1">
              <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest font-mono block">
                Subscription Plan
              </span>
              <h3 className="text-xl font-black text-slate-800 dark:text-white capitalize">
                {activePlanDetails.name}
              </h3>
            </div>
            <div className="p-2 bg-blue-500/10 text-blue-600 dark:text-blue-400 rounded-xl">
              <Sparkles className="w-4 h-4" />
            </div>
          </div>
          <div className="flex justify-between items-center text-[10.5px] border-t border-slate-100 dark:border-slate-850 pt-2.5 mt-2">
            <span className="text-slate-400">{loc.nextRenewal} June 30</span>
            <span className="px-1.5 py-0.5 rounded-md font-bold text-[8.5px] bg-blue-100 text-blue-800 uppercase tracking-wider font-mono">
              {loc.activePlanBadge}
            </span>
          </div>
        </div>

        {/* Card 2: AI Token Volume */}
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-5 shadow-xs flex flex-col justify-between h-36 group hover:border-indigo-500/30 transition-all">
          <div className="flex justify-between items-start">
            <div className="space-y-1">
              <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest font-mono block">
                LLM Tokens (Month)
              </span>
              <h3 className="text-xl font-mono font-black text-slate-800 dark:text-white">
                4.22M <span className="text-xs text-slate-400 font-normal">/ {activePlanDetails.tokenLimit}</span>
              </h3>
            </div>
            <div className="p-2 bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 rounded-xl">
              <Cpu className="w-4 h-4" />
            </div>
          </div>
          <div className="space-y-2 mt-2">
            <div className="w-full h-1.5 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
              <div className="bg-indigo-600 h-full rounded-full" style={{ width: `${Math.min(100, (4.22 / parseFloat(activePlanDetails.tokenLimit.replace(/,/g, ''))) * 100)}%` }} />
            </div>
            <div className="flex justify-between text-[10px] text-slate-400">
              <span className="font-bold text-emerald-500">+12.4% vs last week</span>
              <span className="font-mono">Limit Adherence</span>
            </div>
          </div>
        </div>

        {/* Card 3: Monthly Spend */}
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-5 shadow-xs flex flex-col justify-between h-36 group hover:border-emerald-500/30 transition-all">
          <div className="flex justify-between items-start">
            <div className="space-y-1">
              <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest font-mono block">
                Current Spend (Base)
              </span>
              <h3 className="text-xl font-mono font-black text-slate-800 dark:text-white">
                ${activePriceAdjusted.toLocaleString(undefined, { minimumFractionDigits: 2 })}
              </h3>
            </div>
            <div className="p-2 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 rounded-xl">
              <Coins className="w-4 h-4" />
            </div>
          </div>
          <div className="flex justify-between items-center text-[10px] border-t border-slate-100 dark:border-slate-850 pt-2.5 mt-2">
            <span className="text-slate-400">Projected billing size</span>
            {totalSavings > 0 ? (
              <span className="text-emerald-600 font-bold font-mono">-${totalSavings}/mo saved</span>
            ) : (
              <span className="text-slate-500 font-bold font-mono">No active discounts</span>
            )}
          </div>
        </div>

        {/* Card 4: Remaining Credits */}
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-5 shadow-xs flex flex-col justify-between h-36 group hover:border-violet-500/30 transition-all">
          <div className="flex justify-between items-start">
            <div className="space-y-1">
              <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest font-mono block">
                Farah AI Credits
              </span>
              <h3 className="text-xl font-mono font-black text-slate-800 dark:text-white">
                $450.00
              </h3>
            </div>
            <div className="p-2 bg-violet-500/10 text-violet-600 dark:text-violet-400 rounded-xl">
              <BarChart2 className="w-4 h-4" />
            </div>
          </div>
          <div className="space-y-2 mt-2">
            <div className="w-full h-1.5 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
              <div className="bg-violet-500 h-full rounded-full" style={{ width: '65%' }} />
            </div>
            <div className="flex justify-between text-[10px] text-slate-400">
              <span className="text-slate-500 font-semibold">$150.00 consumed</span>
              <span className="font-mono">Expires Dec 31</span>
            </div>
          </div>
        </div>
      </div>

      {/* ─── Main Grid Layout (Section 2, 3, 5, 6, 7) ─── */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* LEFT TWO-THIRDS PANEL */}
        <div className="lg:col-span-2 space-y-6">
          
          {/* Subscriptions & Plan Info (Section 2) */}
          <div className="bg-gradient-to-br from-slate-900 to-slate-950 border border-slate-850 rounded-3xl p-6 text-white shadow-xl relative overflow-hidden flex flex-col justify-between min-h-64">
            <div className="absolute top-0 right-0 w-64 h-64 bg-blue-600/10 rounded-full blur-3xl pointer-events-none" />
            
            <div className="space-y-4">
              <div className="flex justify-between items-center">
                <div className="flex items-center gap-2">
                  <span className="px-3 py-1 bg-blue-500/20 text-blue-400 rounded-full text-[10px] font-bold tracking-wider uppercase font-mono border border-blue-500/30">
                    {loc.planGrowth}
                  </span>
                  <span className="px-3 py-1 bg-slate-850 text-slate-350 rounded-full text-[10px] font-bold tracking-wider uppercase font-mono border border-slate-800">
                    {paymentCard.brand} ending in {paymentCard.last4}
                  </span>
                </div>
                <div className="p-2 bg-blue-500/10 text-blue-400 rounded-full">
                  <ShieldCheck className="w-5 h-5" />
                </div>
              </div>

              <div className="space-y-1">
                <h3 className="text-2xl font-black tracking-tight flex items-center gap-2">
                  <span>Acme Enterprise Operations Plan</span>
                  <span className="text-xs bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 px-2.5 py-0.5 rounded-full font-bold uppercase font-mono">
                    {loc.activePlanBadge}
                  </span>
                </h3>
                <p className="text-xs text-slate-400 leading-relaxed max-w-xl">
                  {loc.activePlanDesc} Scaled throughput with Pinecone multi-shards, Plivo dedicated SIP trunking gateways, and Farah AI automated routing policies.
                </p>
              </div>

              {/* Limit indicators list */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 pt-3 text-xs">
                <div className="space-y-1 bg-slate-950/60 p-3 rounded-2xl border border-slate-800/80">
                  <span className="text-[10px] text-slate-500 uppercase tracking-wider block font-mono">Workspace Seats</span>
                  <span className="font-bold text-slate-200 font-mono">28 / {activePlanDetails.seatLimit}</span>
                </div>
                <div className="space-y-1 bg-slate-950/60 p-3 rounded-2xl border border-slate-800/80">
                  <span className="text-[10px] text-slate-500 uppercase tracking-wider block font-mono">Speech Minutes</span>
                  <span className="font-bold text-slate-200 font-mono">1,820 / {activePlanDetails.voiceLimit}</span>
                </div>
                <div className="space-y-1 bg-slate-950/60 p-3 rounded-2xl border border-slate-800/80">
                  <span className="text-[10px] text-slate-500 uppercase tracking-wider block font-mono">Vector Storage</span>
                  <span className="font-bold text-slate-200 font-mono">85K / {activePlanDetails.vectorLimit}</span>
                </div>
                <div className="space-y-1 bg-slate-950/60 p-3 rounded-2xl border border-slate-800/80">
                  <span className="text-[10px] text-slate-500 uppercase tracking-wider block font-mono">Renew Cost</span>
                  <span className="font-bold text-slate-200 font-mono">${activePriceAdjusted}/mo</span>
                </div>
              </div>
            </div>

            <div className="border-t border-slate-850 pt-5 mt-6 flex flex-col sm:flex-row gap-4 justify-between sm:items-center text-xs">
              <div className="space-y-0.5">
                <span className="text-slate-450 block font-semibold">{loc.nextRenewal} June 30, 2026 (Automatic)</span>
                <span className="text-[10px] text-slate-500 block">Renewal charges will be billed directly to primary payment instrument.</span>
              </div>
              <button 
                onClick={() => setShowCompareModal(true)}
                className="px-4.5 py-2.5 bg-blue-600 hover:bg-blue-750 active:scale-95 text-white font-bold rounded-2xl transition-all text-xs uppercase tracking-wider border border-blue-500/20 cursor-pointer self-start sm:self-center"
              >
                {loc.btnManageSub}
              </button>
            </div>
          </div>

          {/* AI & Omnichannel Usage Analytics (Section 3) */}
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-xs space-y-6">
            <div>
              <h3 className="font-black text-xs text-slate-700 dark:text-slate-300 uppercase tracking-wider font-mono">
                {loc.resourceUsageTitle}
              </h3>
              <p className="text-[11px] text-slate-500 mt-1">
                {loc.resourceUsageSubtitle}
              </p>
            </div>

            {/* Daily SVG usage chart */}
            <div className="space-y-4">
              <div className="flex justify-between items-center">
                <div className="space-y-0.5">
                  <span className="text-[10.5px] uppercase font-bold text-slate-500 font-mono block">SaaS API Consumption (7 Days)</span>
                  <span className="text-xs text-slate-400">Cumulative transactional gateway calls across web chat, Twilio voice, and WhatsApp.</span>
                </div>
                <span className="text-[11px] font-bold text-emerald-500 px-2 py-0.5 bg-emerald-100 dark:bg-emerald-950/20 rounded-md font-mono">
                  Peak: 22.1K/day
                </span>
              </div>

              {/* Inline SVG Chart */}
              <div className="bg-slate-50 dark:bg-slate-950 border border-slate-100 dark:border-slate-850 p-4 rounded-3xl">
                <svg className="w-full h-48 overflow-visible" viewBox="0 0 600 220" preserveAspectRatio="none">
                  {/* Grids */}
                  <line x1="50" y1="20" x2="550" y2="20" stroke="#f1f5f9" className="dark:stroke-slate-850" strokeWidth="1" />
                  <line x1="50" y1="80" x2="550" y2="80" stroke="#f1f5f9" className="dark:stroke-slate-850" strokeWidth="1" />
                  <line x1="50" y1="140" x2="550" y2="140" stroke="#f1f5f9" className="dark:stroke-slate-850" strokeWidth="1" />
                  <line x1="50" y1="200" x2="550" y2="200" stroke="#e2e8f0" className="dark:stroke-slate-800" strokeWidth="1.5" />
                  
                  {/* Axis labels */}
                  <text x="15" y="24" className="text-[9px] fill-slate-400 font-bold font-mono">30K</text>
                  <text x="15" y="84" className="text-[9px] fill-slate-400 font-bold font-mono">20K</text>
                  <text x="15" y="144" className="text-[9px] fill-slate-400 font-bold font-mono">10K</text>
                  <text x="15" y="204" className="text-[9px] fill-slate-400 font-bold font-mono">0K</text>

                  {/* Shaded Area */}
                  <path 
                    d="M 50 200 L 50 128 L 130 110 L 210 134 L 290 92 L 370 68 L 450 116 L 530 86 L 530 200 Z" 
                    fill="url(#chartGradient)" 
                  />
                  
                  {/* Line */}
                  <path 
                    d="M 50 128 L 130 110 L 210 134 L 290 92 L 370 68 L 450 116 L 530 86" 
                    fill="none" 
                    stroke="#2563eb" 
                    strokeWidth="2.5" 
                    strokeLinecap="round" 
                    strokeLinejoin="round" 
                  />

                  {/* Gradient definitions */}
                  <defs>
                    <linearGradient id="chartGradient" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="0%" stopColor="#3b82f6" stopOpacity="0.25" />
                      <stop offset="100%" stopColor="#3b82f6" stopOpacity="0.0" />
                    </linearGradient>
                  </defs>

                  {/* Data Points */}
                  {chartData.map((val, idx) => {
                    const xPoints = [50, 130, 210, 290, 370, 450, 530];
                    const yPoints = [128, 110, 134, 92, 68, 116, 86];
                    return (
                      <g key={idx} className="group/dot cursor-pointer">
                        <circle 
                          cx={xPoints[idx]} 
                          cy={yPoints[idx]} 
                          r="4" 
                          fill="#3b82f6" 
                          stroke="#ffffff" 
                          strokeWidth="2" 
                          className="hover:r-5 hover:fill-blue-700 transition-all"
                        />
                        {/* Hover Tooltip inside SVG */}
                        <rect 
                          x={xPoints[idx] - 25} 
                          y={yPoints[idx] - 30} 
                          width="50" 
                          height="18" 
                          rx="4" 
                          fill="#0f172a" 
                          className="opacity-0 group-hover/dot:opacity-100 transition-opacity" 
                        />
                        <text 
                          x={xPoints[idx]} 
                          y={yPoints[idx] - 18} 
                          textAnchor="middle" 
                          className="text-[9px] font-bold font-mono fill-white opacity-0 group-hover/dot:opacity-100 transition-opacity"
                        >
                          {val}K
                        </text>
                      </g>
                    );
                  })}

                  {/* Weekday labels */}
                  {chartDays.map((day, idx) => {
                    const xLabels = [50, 130, 210, 290, 370, 450, 530];
                    return (
                      <text 
                        key={idx} 
                        x={xLabels[idx]} 
                        y="218" 
                        textAnchor="middle" 
                        className="text-[9.5px] fill-slate-400 font-bold"
                      >
                        {day}
                      </text>
                    );
                  })}
                </svg>
              </div>
            </div>

            {/* Omnichannel breakdowns progress list */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 pt-2">
              <div className="space-y-4">
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest font-mono block">AI Chatbot Channels</span>
                
                {/* WhatsApp */}
                <div className="space-y-1.5 text-xs font-semibold">
                  <div className="flex justify-between text-slate-500">
                    <span className="flex items-center gap-1.5">
                      <MessageSquare className="w-3.5 h-3.5 text-green-500" />
                      WhatsApp Conversations
                    </span>
                    <span className="font-mono text-slate-700 dark:text-slate-300">12,420 / 25,000</span>
                  </div>
                  <div className="w-full h-1.5 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                    <div className="bg-emerald-500 h-full rounded-full" style={{ width: '49.6%' }} />
                  </div>
                </div>

                {/* Email Support */}
                <div className="space-y-1.5 text-xs font-semibold">
                  <div className="flex justify-between text-slate-500">
                    <span className="flex items-center gap-1.5">
                      <BarChart2 className="w-3.5 h-3.5 text-blue-500" />
                      Email Ticket Audits
                    </span>
                    <span className="font-mono text-slate-700 dark:text-slate-300">8,520 / 10,000</span>
                  </div>
                  <div className="w-full h-1.5 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                    <div className="bg-blue-500 h-full rounded-full" style={{ width: '85.2%' }} />
                  </div>
                </div>
              </div>

              <div className="space-y-4">
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest font-mono block">Compute & RAG Indexes</span>
                
                {/* RAG Searches */}
                <div className="space-y-1.5 text-xs font-semibold">
                  <div className="flex justify-between text-slate-500">
                    <span className="flex items-center gap-1.5">
                      <HardDrive className="w-3.5 h-3.5 text-indigo-500" />
                      Vector DB Queries
                    </span>
                    <span className="font-mono text-slate-700 dark:text-slate-300">45,190 / 100,000</span>
                  </div>
                  <div className="w-full h-1.5 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                    <div className="bg-indigo-500 h-full rounded-full" style={{ width: '45.1%' }} />
                  </div>
                </div>

                {/* Voice Call routing */}
                <div className="space-y-1.5 text-xs font-semibold">
                  <div className="flex justify-between text-slate-500">
                    <span className="flex items-center gap-1.5">
                      <Phone className="w-3.5 h-3.5 text-rose-500" />
                      SIP Voice Minuteness
                    </span>
                    <span className="font-mono text-slate-700 dark:text-slate-300">1,820 / {activePlanDetails.voiceLimit}</span>
                  </div>
                  <div className="w-full h-1.5 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                    <div className="bg-rose-500 h-full rounded-full" style={{ width: `${(1820 / parseFloat(activePlanDetails.voiceLimit.replace(/,/g, ''))) * 100}%` }} />
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Resource Consumption & Warnings (Section 6) */}
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-xs space-y-4">
            <div>
              <h3 className="font-black text-xs text-slate-700 dark:text-slate-300 uppercase tracking-wider font-mono">
                Platform Resource Constraints & Monitoring
              </h3>
              <p className="text-[11px] text-slate-500 mt-1">
                Real-time warnings on hard tenant resources limits for storage database compaction.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Vector database compaction warning */}
              <div className="p-4 bg-slate-50 dark:bg-slate-950 border border-slate-100 dark:border-slate-850 rounded-2xl space-y-2">
                <div className="flex justify-between items-center">
                  <span className="font-bold text-xs text-slate-800 dark:text-white">{loc.limitComputeTitle}</span>
                  <span className="px-2 py-0.5 rounded-md font-bold text-[9px] bg-amber-100 text-amber-800 uppercase tracking-wider font-mono">
                    Warning (85.4%)
                  </span>
                </div>
                <div className="w-full h-2 bg-slate-200 dark:bg-slate-800 rounded-full overflow-hidden">
                  <div className="bg-amber-500 h-full rounded-full" style={{ width: '85.4%' }} />
                </div>
                <div className="flex justify-between text-[10.5px] text-slate-400 font-semibold pt-1">
                  <span>85,420 / {activePlanDetails.vectorLimit} vectors</span>
                  <span className="text-red-500">{loc.overageAlert}</span>
                </div>
              </div>

              {/* Workspace Seat allocation */}
              <div className="p-4 bg-slate-50 dark:bg-slate-950 border border-slate-100 dark:border-slate-850 rounded-2xl space-y-2">
                <div className="flex justify-between items-center">
                  <span className="font-bold text-xs text-slate-800 dark:text-white">{loc.limitSeatsTitle}</span>
                  <span className="px-2 py-0.5 rounded-md font-bold text-[9px] bg-emerald-100 text-emerald-800 uppercase tracking-wider font-mono">
                    Normal (56.0%)
                  </span>
                </div>
                <div className="w-full h-2 bg-slate-200 dark:bg-slate-800 rounded-full overflow-hidden">
                  <div className="bg-emerald-500 h-full rounded-full" style={{ width: '56%' }} />
                </div>
                <div className="flex justify-between text-[10.5px] text-slate-400 font-semibold pt-1">
                  <span>28 / {activePlanDetails.seatLimit} seats occupied</span>
                  <span>{loc.exhaustionProjected} None</span>
                </div>
              </div>
            </div>
          </div>

        </div>

        {/* RIGHT SIDEBAR PANEL */}
        <div className="space-y-6">
          
          {/* Cost Optimization Center (Section 7) */}
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-xs space-y-4">
            <div className="space-y-1">
              <h3 className="font-black text-xs text-slate-700 dark:text-slate-300 uppercase tracking-wider font-mono flex items-center gap-1.5">
                <Cpu className="w-4 h-4 text-blue-500" />
                {loc.optTitle}
              </h3>
              <p className="text-[11px] text-slate-500 leading-relaxed">
                {loc.optSubtitle}
              </p>
            </div>

            {/* Savings Total Display */}
            {totalSavings > 0 && (
              <div className="bg-emerald-500/10 border border-emerald-500/20 rounded-2xl p-3 flex justify-between items-center text-xs animate-in zoom-in-95">
                <span className="font-bold text-emerald-850 dark:text-emerald-400">Total Applied Monthly Savings:</span>
                <span className="font-mono font-black text-emerald-600 dark:text-emerald-400 text-sm">-${totalSavings}/mo</span>
              </div>
            )}

            {/* Recommendations List */}
            <div className="space-y-3">
              {optimizationList.map((opt) => {
                const isApplied = appliedOpts.includes(opt.id);
                return (
                  <div 
                    key={opt.id} 
                    className={`p-3.5 border rounded-2xl space-y-2.5 transition-all ${
                      isApplied 
                        ? 'bg-slate-50/50 dark:bg-slate-950/20 border-slate-200 dark:border-slate-850 opacity-60' 
                        : 'bg-slate-50 dark:bg-slate-950/50 border-slate-100 dark:border-slate-850 hover:border-slate-200 dark:hover:border-slate-800'
                    }`}
                  >
                    <div className="flex justify-between items-start gap-2">
                      <span className="font-bold text-[11.5px] leading-tight text-slate-800 dark:text-white">
                        {isRtl ? opt.titleAr : opt.titleEn}
                      </span>
                      <span className="px-2 py-0.5 bg-emerald-100 dark:bg-emerald-950/40 text-emerald-800 dark:text-emerald-400 rounded text-[9.5px] font-bold font-mono shrink-0">
                        +${opt.savings}/mo
                      </span>
                    </div>
                    <p className="text-[10px] text-slate-500 leading-relaxed font-semibold">
                      {isRtl ? opt.descriptionAr : opt.descriptionEn}
                    </p>
                    <div className="flex justify-between items-center pt-1 border-t border-slate-100 dark:border-slate-850">
                      <span className="text-[9.5px] font-mono text-slate-450 uppercase">Category: {opt.category}</span>
                      <button
                        type="button"
                        onClick={() => handleApplyOpt(opt.id, opt.savings, isRtl ? opt.titleAr : opt.titleEn)}
                        disabled={isApplied || !canEdit}
                        className={`px-3 py-1.5 rounded-xl font-bold text-[10px] transition-all flex items-center gap-1 cursor-pointer ${
                          isApplied || !canEdit
                            ? 'bg-slate-200 dark:bg-slate-800 text-slate-400 dark:text-slate-650 cursor-not-allowed'
                            : 'bg-blue-600 hover:bg-blue-750 text-white active:scale-95'
                        }`}
                        title={!isApplied && !canEdit ? "Requires Edit Permission" : undefined}
                      >
                        {isApplied && <Check className="w-3.5 h-3.5" />}
                        <span>{isApplied ? loc.btnAppliedOpt : loc.btnApplyOpt}</span>
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Payment Method & Contact Details (Section 5) */}
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-xs space-y-5">
            <div>
              <h3 className="font-black text-xs text-slate-700 dark:text-slate-300 uppercase tracking-wider font-mono flex items-center gap-1.5">
                <CreditCard className="w-4 h-4 text-blue-500" />
                {loc.paymentTitle}
              </h3>
              <p className="text-[11px] text-slate-500 mt-1">
                {loc.paymentSubtitle}
              </p>
            </div>

            {/* Premium Gold Gradient Credit Card */}
            <div className="bg-gradient-to-br from-amber-500 via-amber-600 to-amber-800 rounded-2xl p-5 text-white shadow-md relative overflow-hidden h-36 flex flex-col justify-between">
              <div className="absolute top-0 right-0 w-24 h-24 bg-white/10 rounded-full blur-xl pointer-events-none" />
              <div className="flex justify-between items-start">
                <div className="space-y-1">
                  <span className="text-[9px] uppercase tracking-widest font-mono text-amber-200 font-bold block">Gold Corporate</span>
                  <span className="font-mono text-sm tracking-widest font-black">•••• •••• •••• {paymentCard.last4}</span>
                </div>
                <div className="text-right text-xs font-bold font-mono tracking-wider italic text-amber-100">
                  {paymentCard.brand.toUpperCase()}
                </div>
              </div>

              {/* Chip Layout */}
              <div className="w-8 h-6 bg-yellow-200/40 rounded-md border border-white/20 self-start" />

              <div className="flex justify-between items-end text-[10.5px] font-mono text-amber-100">
                <div className="space-y-0.5">
                  <span className="text-[8px] uppercase text-amber-300 font-bold block">{loc.cardHolder}</span>
                  <span className="font-bold truncate block max-w-40" title={paymentCard.holder}>{paymentCard.holder}</span>
                </div>
                <div className="space-y-0.5 text-right">
                  <span className="text-[8px] uppercase text-amber-300 font-bold block">{loc.cardExpiry}</span>
                  <span className="font-bold">{paymentCard.expiry}</span>
                </div>
              </div>
            </div>

            {/* Billing emails / contacts */}
            <div className="space-y-3 pt-2 text-xs">
              {/* Emails */}
              <div className="space-y-1">
                <span className="text-[10px] text-slate-450 uppercase font-bold tracking-wider font-mono block">
                  {loc.billingEmailTitle}
                </span>
                {billingEmails.map((em, idx) => (
                  <span key={idx} className="block font-mono font-bold text-slate-700 dark:text-slate-300">
                    {em}
                  </span>
                ))}
              </div>

              {/* VAT & Address */}
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <span className="text-[10px] text-slate-450 uppercase font-bold tracking-wider font-mono block">
                    {loc.vatIdLabel}
                  </span>
                  <span className="font-mono font-bold text-slate-700 dark:text-slate-300">{vatId}</span>
                </div>
                <div className="space-y-1">
                  <span className="text-[10px] text-slate-450 uppercase font-bold tracking-wider font-mono block">
                    {loc.billingAddressLabel}
                  </span>
                  <span className="font-bold text-slate-750 dark:text-slate-350 leading-tight block">
                    {billingAddress.line1}, {billingAddress.city}, {billingAddress.country}
                  </span>
                </div>
              </div>
            </div>

            <button
              onClick={handleOpenEditModal}
              disabled={!canEdit}
              className={`w-full py-2.5 font-bold rounded-2xl text-[10.5px] uppercase tracking-wider transition-all cursor-pointer ${
                !canEdit
                  ? 'bg-slate-105 border-slate-205 text-slate-400 dark:bg-slate-900 dark:border-slate-850 dark:text-slate-600 cursor-not-allowed opacity-60'
                  : 'bg-slate-50 hover:bg-slate-100 dark:bg-slate-950 dark:hover:bg-slate-900 border border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-300'
              }`}
              title={!canEdit ? "Requires Edit Permission" : undefined}
            >
              {loc.btnEditBilling}
            </button>
          </div>

        </div>

      </div>

      {/* ─── Invoices Table (Section 4) ─── */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-xs space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-slate-100 dark:border-slate-850">
          <div className="flex items-center gap-2">
            <Receipt className="w-4 h-4 text-blue-500" />
            <h3 className="font-black text-xs text-slate-700 dark:text-slate-300 uppercase font-mono">
              {loc.invoiceTableTitle}
            </h3>
          </div>
          
          {/* Invoice status filter tabs */}
          <div className="flex gap-1.5 p-1 bg-slate-50 dark:bg-slate-950 border border-slate-200/50 dark:border-slate-850 rounded-2xl w-fit">
            {(['all', 'paid', 'failed'] as const).map((filter) => (
              <button
                key={filter}
                onClick={() => setInvoiceFilter(filter)}
                className={`px-3 py-1 rounded-xl text-[9px] uppercase tracking-wider font-bold transition-all cursor-pointer ${
                  invoiceFilter === filter
                    ? 'bg-white dark:bg-slate-900 text-blue-600 shadow-xs'
                    : 'text-slate-400 hover:text-slate-600 dark:hover:text-slate-300'
                }`}
              >
                {filter === 'all' ? 'All' : filter === 'paid' ? 'Paid' : 'Failed'}
              </button>
            ))}
          </div>
        </div>

        <div className="overflow-x-auto min-w-0">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="border-b border-slate-100 dark:border-slate-855 text-slate-400 font-bold">
                <th className="pb-3 px-4">{loc.invoiceColRef}</th>
                <th className="pb-3 px-4">{loc.invoiceColPeriod}</th>
                <th className="pb-3 px-4">{loc.invoiceColAmount}</th>
                <th className="pb-3 px-4">Payment Method</th>
                <th className="pb-3 px-4">{loc.invoiceColStatus}</th>
                <th className="pb-3 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-850 text-slate-600 dark:text-slate-300 font-semibold">
              {filteredInvoices.map((inv) => (
                <tr key={inv.id} className="hover:bg-slate-50/50 dark:hover:bg-slate-950/20 group transition-colors">
                  <td className="py-3 px-4 font-mono font-bold text-slate-900 dark:text-white">{inv.id}</td>
                  <td className="py-3 px-4 font-mono text-slate-450 dark:text-slate-400">{inv.period}</td>
                  <td className="py-3 px-4 font-mono text-slate-800 dark:text-slate-200">{inv.amount}</td>
                  <td className="py-3 px-4 font-mono text-slate-450 dark:text-slate-400">{inv.method}</td>
                  <td className="py-3 px-4">
                    {inv.status === 'paid' ? (
                      <span className="px-2 py-0.5 rounded-md text-[8.5px] font-bold font-mono bg-emerald-100 dark:bg-emerald-950/20 text-emerald-800 dark:text-emerald-450 uppercase tracking-wider">
                        Paid
                      </span>
                    ) : (
                      <span className="px-2 py-0.5 rounded-md text-[8.5px] font-bold font-mono bg-rose-100 dark:bg-rose-950/20 text-rose-800 dark:text-rose-450 uppercase tracking-wider animate-pulse">
                        Failed
                      </span>
                    )}
                  </td>
                  <td className="py-3 px-4 text-right">
                    <div className="flex gap-2 justify-end">
                      <button 
                        onClick={() => setSelectedInvoice(inv)}
                        className="px-2.5 py-1.5 border border-slate-200 dark:border-slate-850 bg-white hover:bg-slate-100 dark:bg-slate-900 dark:hover:bg-slate-850 text-slate-700 dark:text-slate-300 rounded-xl transition-all font-bold text-[10px] cursor-pointer"
                      >
                        {loc.btnView}
                      </button>
                      <button 
                        onClick={() => handleDownloadPdf(inv.id)}
                        disabled={!canExport}
                        className={`px-2.5 py-1.5 border border-slate-200 dark:border-slate-850 rounded-xl transition-all font-bold text-[10px] cursor-pointer ${
                          !canExport
                            ? 'bg-slate-105 dark:bg-slate-850 text-slate-400 dark:text-slate-600 cursor-not-allowed'
                            : 'bg-slate-50 hover:bg-slate-100 dark:bg-slate-950 dark:hover:bg-slate-900 text-slate-655 dark:text-slate-300'
                        }`}
                        title={!canExport ? "Requires Export Permission" : undefined}
                      >
                        <Download className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
              {filteredInvoices.length === 0 && (
                <tr>
                  <td colSpan={6} className="py-8 text-center text-slate-400 font-medium">
                    No invoices matching current filter criteria.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* ─── MODAL 1: Compare Plans (Upgrade Center) ─── */}
      {showCompareModal && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl max-w-3xl w-full max-h-[85vh] overflow-hidden flex flex-col shadow-2xl animate-in zoom-in-95" dir={isRtl ? 'rtl' : 'ltr'}>
            <div className="p-5 border-b border-slate-100 dark:border-slate-850 flex justify-between items-center bg-slate-55/30 dark:bg-slate-950/20">
              <div className="space-y-0.5">
                <h3 className="font-black text-sm text-slate-800 dark:text-white uppercase tracking-wider font-mono">
                  {loc.modalCompareTitle}
                </h3>
                <p className="text-[10.5px] text-slate-500">
                  {loc.modalCompareSubtitle}
                </p>
              </div>
              <button 
                onClick={() => setShowCompareModal(false)}
                className="p-1.5 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-full text-slate-450 cursor-pointer"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="flex-1 overflow-y-auto p-6 space-y-6">
              {/* Tiers Pricing Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
                {(['starter', 'growth', 'enterprise', 'ai_plus'] as const).map((tier) => {
                  const details = planLimits[tier];
                  const isCurrent = activePlan === tier;
                  return (
                    <div 
                      key={tier}
                      className={`p-4 border rounded-2xl flex flex-col justify-between h-48 transition-all ${
                        isCurrent 
                          ? 'border-blue-500 bg-blue-500/5 dark:bg-blue-500/10' 
                          : 'border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-950'
                      }`}
                    >
                      <div className="space-y-1">
                        <span className="text-[8px] font-bold text-slate-400 uppercase tracking-widest font-mono block">Plan Category</span>
                        <h4 className="font-black text-xs text-slate-800 dark:text-white capitalize">{details.name}</h4>
                        <div className="pt-2">
                          <span className="text-xl font-bold font-mono">${details.basePrice}</span>
                          <span className="text-[10px] text-slate-400 font-semibold">/mo</span>
                        </div>
                      </div>
                      <button
                        onClick={() => handleSwitchPlan(tier)}
                        disabled={isCurrent || !canManage}
                        className={`w-full py-2 rounded-xl text-[10px] font-bold transition-all uppercase tracking-wider cursor-pointer ${
                          isCurrent || !canManage
                            ? 'bg-slate-200 dark:bg-slate-850 text-slate-400 dark:text-slate-550 cursor-not-allowed border border-transparent'
                            : 'bg-blue-600 hover:bg-blue-750 text-white active:scale-95'
                        }`}
                        title={!isCurrent && !canManage ? "Requires Manage Permission" : undefined}
                      >
                        {isCurrent ? loc.btnActivePlan : loc.btnSwitchPlan}
                      </button>
                    </div>
                  );
                })}
              </div>

              {/* Feature Matrix */}
              <div className="space-y-3">
                <h4 className="font-bold text-xs text-slate-800 dark:text-white uppercase tracking-wider font-mono">
                  {loc.featureMatrixTitle}
                </h4>
                <div className="overflow-x-auto">
                  <table className="w-full text-[10.5px] border-collapse text-left">
                    <thead>
                      <tr className="border-b border-slate-100 dark:border-slate-850 text-slate-400 font-bold">
                        <th className="pb-2">Capabilities</th>
                        <th className="pb-2 capitalize">{loc.planStarter}</th>
                        <th className="pb-2 capitalize">{loc.planGrowth}</th>
                        <th className="pb-2 capitalize">{loc.planEnterprise}</th>
                        <th className="pb-2 capitalize">{loc.planEnterprisePlus}</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 dark:divide-slate-850 text-slate-655 dark:text-slate-350 font-semibold">
                      <tr>
                        <td className="py-2 font-bold">LLM Token Allotment</td>
                        <td className="py-2 font-mono">1.0 M</td>
                        <td className="py-2 font-mono">5.0 M</td>
                        <td className="py-2 font-mono">10.0 M</td>
                        <td className="py-2 font-mono">50.0 M</td>
                      </tr>
                      <tr>
                        <td className="py-2 font-bold">ASR Speech Minutes</td>
                        <td className="py-2 font-mono">500</td>
                        <td className="py-2 font-mono">2,000</td>
                        <td className="py-2 font-mono">5,000</td>
                        <td className="py-2 font-mono">25,000</td>
                      </tr>
                      <tr>
                        <td className="py-2 font-bold">Workspace Seat Allotment</td>
                        <td className="py-2 font-mono">5</td>
                        <td className="py-2 font-mono">15</td>
                        <td className="py-2 font-mono">50</td>
                        <td className="py-2 font-mono">150</td>
                      </tr>
                      <tr>
                        <td className="py-2 font-bold">Dedicated Support Manager</td>
                        <td className="py-2 text-rose-500">No</td>
                        <td className="py-2 text-rose-500">No</td>
                        <td className="py-2 text-emerald-500 font-bold">Yes (4h SLA)</td>
                        <td className="py-2 text-emerald-500 font-bold">Yes (15m VIP SLA)</td>
                      </tr>
                      <tr>
                        <td className="py-2 font-bold">Custom Training Loop Engine</td>
                        <td className="py-2 text-rose-500">No</td>
                        <td className="py-2 text-rose-500">No</td>
                        <td className="py-2 text-emerald-500 font-bold">Yes</td>
                        <td className="py-2 text-emerald-500 font-bold">Yes</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

            <div className="p-4 border-t border-slate-100 dark:border-slate-850 bg-slate-50 dark:bg-slate-950 text-right">
              <button 
                onClick={() => setShowCompareModal(false)}
                className="px-4 py-2 bg-slate-200 dark:bg-slate-800 hover:bg-slate-300 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-350 font-bold rounded-2xl text-xs cursor-pointer"
              >
                {loc.modalClose}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ─── MODAL 2: Invoice Detail Preview (Section 4) ─── */}
      {selectedInvoice && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl max-w-md w-full shadow-2xl animate-in zoom-in-95" dir={isRtl ? 'rtl' : 'ltr'}>
            <div className="p-5 border-b border-slate-100 dark:border-slate-850 flex justify-between items-center bg-slate-55/30 dark:bg-slate-950/20">
              <div className="space-y-0.5">
                <h3 className="font-black text-sm text-slate-800 dark:text-white uppercase tracking-wider font-mono">
                  {loc.invoicePreviewTitle}: {selectedInvoice.id}
                </h3>
                <p className="text-[10.5px] text-slate-500">{loc.invoicePreviewDesc}</p>
              </div>
              <button 
                onClick={() => setSelectedInvoice(null)}
                className="p-1.5 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-full text-slate-450 cursor-pointer"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="p-6 space-y-4 text-xs font-semibold">
              {/* Metadata */}
              <div className="grid grid-cols-2 gap-4 pb-3 border-b border-slate-100 dark:border-slate-850 text-slate-550">
                <div className="space-y-0.5">
                  <span className="text-[10px] text-slate-400 uppercase font-mono tracking-wider block">Billing Period</span>
                  <span className="font-mono text-slate-700 dark:text-slate-350">{selectedInvoice.period}</span>
                </div>
                <div className="space-y-0.5 text-right">
                  <span className="text-[10px] text-slate-400 uppercase font-mono tracking-wider block">Issue Date</span>
                  <span className="font-mono text-slate-700 dark:text-slate-350">{selectedInvoice.date}</span>
                </div>
              </div>

              {/* Items charges */}
              <div className="space-y-3 py-2">
                <h4 className="font-bold text-[10px] text-slate-450 uppercase tracking-wider font-mono">Line Item Summary</h4>
                
                {/* Item 1 */}
                <div className="flex justify-between items-center text-slate-700 dark:text-slate-300">
                  <div className="space-y-0.5">
                    <span>Base Tier Subscription - Enterprise</span>
                    <span className="text-[9.5px] text-slate-450 block font-normal">Standard 50 agent seats and 5,000 Voice Minutes.</span>
                  </div>
                  <span className="font-mono">{selectedInvoice.amount}</span>
                </div>

                {/* Item 2 */}
                <div className="flex justify-between items-center text-slate-750 dark:text-slate-300">
                  <div className="space-y-0.5">
                    <span>AI Token Overages (4.2M consumed)</span>
                    <span className="text-[9.5px] text-slate-450 block font-normal">Overage calculations. No additional charge under limit.</span>
                  </div>
                  <span className="font-mono">$0.00</span>
                </div>
              </div>

              {/* Totals */}
              <div className="pt-3 border-t border-slate-100 dark:border-slate-850 space-y-1.5 text-slate-655">
                <div className="flex justify-between items-center">
                  <span>Subtotal</span>
                  <span className="font-mono">{selectedInvoice.amount}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span>VAT Tax (15.0%)</span>
                  <span className="font-mono">Included</span>
                </div>
                <div className="flex justify-between items-center text-slate-900 dark:text-white font-black text-sm pt-2 border-t border-slate-100 dark:border-slate-850">
                  <span>Total Amount</span>
                  <span className="font-mono">{selectedInvoice.amount}</span>
                </div>
              </div>

              {/* Method */}
              <div className="p-3 bg-slate-50 dark:bg-slate-950 border border-slate-100 dark:border-slate-850 rounded-2xl flex justify-between items-center text-[10.5px]">
                <span className="text-slate-450">Payment Method:</span>
                <span className="font-mono text-slate-750 dark:text-slate-300 font-bold">{selectedInvoice.method}</span>
              </div>
            </div>

             <div className="p-4 border-t border-slate-100 dark:border-slate-850 bg-slate-50 dark:bg-slate-950 flex justify-between gap-3">
               <button 
                onClick={() => handleDownloadPdf(selectedInvoice.id)}
                disabled={!canExport}
                className={`px-4 py-2 text-white font-bold rounded-2xl text-xs flex items-center gap-1.5 cursor-pointer transition-all ${
                  !canExport
                    ? 'bg-slate-200 dark:bg-slate-800 text-slate-400 dark:text-slate-650 cursor-not-allowed border border-transparent'
                    : 'bg-blue-600 hover:bg-blue-750 active:scale-95'
                }`}
                title={!canExport ? "Requires Export Permission" : undefined}
              >
                <Download className="w-4 h-4" />
                <span>{loc.btnDownload}</span>
              </button>
              <button 
                onClick={() => setSelectedInvoice(null)}
                className="px-4 py-2 bg-slate-200 dark:bg-slate-800 hover:bg-slate-300 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-350 font-bold rounded-2xl text-xs cursor-pointer"
              >
                {loc.modalClose}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ─── MODAL 3: Edit Contacts / Billing Details (Section 5) ─── */}
      {showEditModal && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <form 
            onSubmit={handleSaveBilling}
            className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl max-w-md w-full shadow-2xl animate-in zoom-in-95 flex flex-col overflow-hidden" 
            dir={isRtl ? 'rtl' : 'ltr'}
          >
            <div className="p-5 border-b border-slate-100 dark:border-slate-850 flex justify-between items-center bg-slate-55/30 dark:bg-slate-950/20">
              <div className="space-y-0.5">
                <h3 className="font-black text-sm text-slate-800 dark:text-white uppercase tracking-wider font-mono">
                  Edit Billing Parameters
                </h3>
                <p className="text-[10.5px] text-slate-500">Modify accounting email records and default address.</p>
              </div>
              <button 
                type="button"
                onClick={() => setShowEditModal(false)}
                className="p-1.5 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-full text-slate-450 cursor-pointer"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="p-6 space-y-4 text-xs font-semibold text-slate-850 dark:text-slate-250">
              
              {/* Credit Card Last 4 digits */}
              <div className="space-y-1.5">
                <label className="block text-slate-450 uppercase font-mono text-[10px]">Mastercard (Last 4 Digits only)</label>
                <input 
                  type="text" 
                  maxLength={4}
                  value={editCardLast4} 
                  onChange={(e) => setEditCardLast4(e.target.value)}
                  className="w-full px-3.5 py-2.5 border border-slate-200 dark:border-slate-850 bg-slate-50 dark:bg-slate-950 rounded-xl focus:outline-none focus:border-blue-500 font-mono text-slate-800 dark:text-white"
                  placeholder="8842"
                  required
                />
              </div>

              {/* Billing contacts */}
              <div className="space-y-1.5">
                <label className="block text-slate-450 uppercase font-mono text-[10px]">Finance Contacts (Comma Separated)</label>
                <input 
                  type="text" 
                  value={editEmailsText} 
                  onChange={(e) => setEditEmailsText(e.target.value)}
                  className="w-full px-3.5 py-2.5 border border-slate-200 dark:border-slate-850 bg-slate-50 dark:bg-slate-950 rounded-xl focus:outline-none focus:border-blue-500 font-mono text-slate-800 dark:text-white"
                  placeholder="billing@company.com"
                  required
                />
              </div>

              {/* Billing Address Line 1 */}
              <div className="space-y-1.5">
                <label className="block text-slate-450 uppercase font-mono text-[10px]">Billing Street Address</label>
                <input 
                  type="text" 
                  value={editAddressLine} 
                  onChange={(e) => setEditAddressLine(e.target.value)}
                  className="w-full px-3.5 py-2.5 border border-slate-200 dark:border-slate-850 bg-slate-50 dark:bg-slate-950 rounded-xl focus:outline-none focus:border-blue-500 text-slate-850 dark:text-white"
                  placeholder="Address Line 1"
                  required
                />
              </div>
            </div>

            <div className="p-4 border-t border-slate-100 dark:border-slate-850 bg-slate-50 dark:bg-slate-950 flex justify-between gap-3">
              <button 
                type="submit"
                className="px-4 py-2 bg-blue-600 hover:bg-blue-750 text-white font-bold rounded-2xl text-xs active:scale-95 transition-all cursor-pointer"
              >
                Save Updates
              </button>
              <button 
                type="button"
                onClick={() => setShowEditModal(false)}
                className="px-4 py-2 bg-slate-200 dark:bg-slate-800 hover:bg-slate-300 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-350 font-bold rounded-2xl text-xs cursor-pointer"
              >
                {loc.modalClose}
              </button>
            </div>
          </form>
        </div>
      )}
    </div>
  );
}

export default BillingTab;
