import React from 'react';
import {
  MessageSquare, Globe, Mail, Phone, Radio, Camera
} from 'lucide-react';

// ─── Self-contained bilingual dictionary ──────────────────────────────────────
export const DICT = {
  en: {
    title: 'Omnichannel Operations Hub',
    description: 'Customize customer contact touchpoints, manage chatbot handoffs, template registers, and live chat widget appearance.',
    activeChannels: 'Active Customer Channels',
    aiAutomationUsage: 'AI Automation Usage',
    liveConversations: 'Live Conversations',
    waDeliveryRate: 'WhatsApp Delivery Rate',
    avgResponseTime: 'Avg Response Time',
    activeSessions: 'Active Chat Sessions',
    catalogTitle: 'Channel Catalog',
    catalogDesc: 'Activate communication channels, define routing modes, SLA baselines, and chatbot triages.',
    colStatus: 'Status',
    colAI: 'AI Enabled',
    colRoutingMode: 'Routing Mode',
    colQueue: 'Assigned Queue',
    colSLA: 'SLA Baseline',
    colVolume: 'Msg Volume',
    configure: 'Configure Operations',
    active: 'Active',
    inactive: 'Inactive',
    bizOpsTitle: 'Business Operations & Routing Policy',
    bizOpsDesc: 'Control operational availability boundaries, primary queue distribution, and human escalation rules.',
    supportHours: 'Support Operations Window',
    bizHours: 'Standard Business Hours (08:00 - 18:00 AST)',
    alwaysOpen: 'Continuous 24/7 Operations',
    primaryQueue: 'Default Dispatch Queue',
    chatbotTriage: 'AI Bot Pre-Triage',
    chatbotTriageDesc: 'Let Farah AI bot intercept and resolve inbound requests before agent allocation.',
    handoffSlider: 'Human Handoff Confidence Limit',
    handoffDesc: 'Escalate to a human agent when bot confidence falls below:',
    languageRouting: 'Language Route Mapping',
    languageRoutingDesc: 'Assign conversations based on customer browser language matching agent skillset.',
    offlineAutoReply: 'Offline Engagement Template',
    waTemplateTitle: 'WhatsApp Template Center',
    waTemplateDesc: 'Create and preview meta-approved notification alerts and quick-replies.',
    colTplName: 'Template Name',
    colCategory: 'Category',
    colLanguage: 'Language',
    colUsage: 'Total Sent',
    colSuccessRate: 'Delivery Rate',
    colStatusLabel: 'Approval State',
    preview: 'Preview Output',
    templateDetails: 'WhatsApp Notification Preview',
    approved: 'Approved',
    pending: 'Pending Verification',
    rejected: 'Rejected',
    webChatTitle: 'Web Chat Customizer',
    webChatDesc: 'Configure greeting text rules, bot avatar visibility, and launcher positioning.',
    primaryColor: 'Widget Accent Theme',
    greetingEn: 'Launcher Welcome Header (EN)',
    greetingAr: 'Launcher Welcome Header (AR)',
    launcherPos: 'Floating Widget Alignment',
    bottomRight: 'Bottom-Right Corner',
    bottomLeft: 'Bottom-Left Corner',
    welcomeFlow: 'Pre-Chat Data Collection',
    collectNameEmail: 'Collect Name & Email before chatting',
    botAvatar: 'Display Agent Avatar Symbol',
    offlineBehavior: 'Offline Connection Routing',
    submitTicket: 'Generate Offline Support Ticket',
    autoReplyOnly: 'Trigger Automated Response Template',
    csatTrigger: 'Auto-Trigger CSAT Post-Interaction',
    livePreview: 'Live Widget Interface Preview',
    farahBot: 'Farah AI Assistant',
    online: 'Online',
    typeMessage: 'Type a message...',
    saveSettings: 'Deploy Tenant Configurations',
    cancel: 'Discard Changes',
    routingState: 'Routing State',
    saveWidgetConfigs: 'Save Widget Settings',
    viewAuditLogs: 'View Audit Logs',
    auditLogsTitle: 'Web Chat Audit Logs',
    colDate: 'Date',
    colUser: 'User',
    colAction: 'Action',
  },
  ar: {
    title: 'مركز عمليات القنوات المتعددة',
    description: 'تخصيص نقاط اتصال العملاء، وإدارة عمليات تحويل البوت، وسجل القوالب، ومظهر ويدجت الدردشة المباشرة.',
    activeChannels: 'قنوات العملاء النشطة',
    aiAutomationUsage: 'استخدام أتمتة الذكاء الاصطناعي',
    liveConversations: 'المحادثات المباشرة النشطة',
    waDeliveryRate: 'معدل تسليم الواتساب',
    avgResponseTime: 'متوسط وقت الاستجابة',
    activeSessions: 'جلسات الدردشة النشطة',
    catalogTitle: 'كتالوج القنوات',
    catalogDesc: 'تفعيل قنوات اتصالات العملاء وتحديد وضع التوجيه وSLA الأساسية وتجربة البوت.',
    colStatus: 'الحالة',
    colAI: 'الذكاء الاصطناعي',
    colRoutingMode: 'وضع التوجيه',
    colQueue: 'الصف المعين',
    colSLA: 'حد SLA الأساسي',
    colVolume: 'حجم الرسائل',
    configure: 'تهيئة العمليات',
    active: 'نشط',
    inactive: 'غير نشط',
    bizOpsTitle: 'العمليات التجارية وسياسة التوجيه',
    bizOpsDesc: 'التحكم في حدود التوافر التشغيلي، وتوزيع الصفوف الافتراضي، وقواعد التصعيد البشري.',
    supportHours: 'نافذة عمليات الدعم',
    bizHours: 'ساعات العمل الرسمية (08:00 - 18:00 AST)',
    alwaysOpen: 'عمليات مستمرة على مدار الساعة 24/7',
    primaryQueue: 'صف التوزيع الافتراضي',
    chatbotTriage: 'فرز تلقائي بالذكاء الاصطناعي',
    chatbotTriageDesc: 'السماح للذكاء الاصطناعي فرح باعتراض وحل الطلبات الواردة قبل تخصيص وكيل.',
    handoffSlider: 'حد ثقة التحويل البشري',
    handoffDesc: 'التصعيد إلى وكيل بشري عندما تقل ثقة البوت عن:',
    languageRouting: 'مزامنة التوجيه اللغوي',
    languageRoutingDesc: 'توجيه المحادثات بناءً على لغة متصفح العميل لتطابق مهارات الوكيل.',
    offlineAutoReply: 'قالب التفاعل خارج أوقات العمل',
    waTemplateTitle: 'مركز قوالب الواتساب',
    waTemplateDesc: 'إنشاء ومعاينة تنبيهات الإشعارات والردود السريعة المعتمدة من Meta.',
    colTplName: 'اسم القالب',
    colCategory: 'الفئة',
    colLanguage: 'اللغة',
    colUsage: 'إجمالي المرسل',
    colSuccessRate: 'معدل التسليم',
    colStatusLabel: 'حالة الاعتماد',
    preview: 'معاينة القالب',
    templateDetails: 'معاينة إشعارات الواتساب',
    approved: 'مقبول',
    pending: 'قيد التحقق',
    rejected: 'مرفوض',
    webChatTitle: 'تخصيص ويدجت الدردشة',
    webChatDesc: 'تهيئة قواعد الترحيب، وظهور الصورة الرمزية للبوت، ومحاذاة المشغل.',
    primaryColor: 'سمة لون الويدجت',
    greetingEn: 'عنوان الترحيب بالإنجليزية',
    greetingAr: 'عنوان الترحيب بالعربية',
    launcherPos: 'محاذاة المشغل العائم',
    bottomRight: 'الزاوية اليمنى السفلية',
    bottomLeft: 'الزاوية اليسرى السفلية',
    welcomeFlow: 'جمع البيانات قبل بدء الدردشة',
    collectNameEmail: 'طلب الاسم والبريد الإلكتروني قبل الدردشة',
    botAvatar: 'عرض رمز الصورة الرمزية للوكيل',
    offlineBehavior: 'توجيه الاتصال خارج أوقات العمل',
    submitTicket: 'إنشاء تذكرة دعم دون اتصال بالإنترنت',
    autoReplyOnly: 'تشغيل قالب الرد التلقائي التنبيهي',
    csatTrigger: 'إطلاق CSAT تلقائياً بعد انتهاء المحادثة',
    livePreview: 'معاينة حية لواجهة الويدجت',
    farahBot: 'فرح - المساعد الذكي',
    online: 'متصل',
    typeMessage: 'اكتب رسالة...',
    saveSettings: 'حفظ إعدادات المستأجر',
    cancel: 'إلغاء التغييرات',
    routingState: 'حالة التوجيه',
    saveWidgetConfigs: 'حفظ إعدادات الويدجت',
    viewAuditLogs: 'عرض سجلات التدقيق',
    auditLogsTitle: 'سجلات تدقيق دردشة الويب',
    colDate: 'التاريخ',
    colUser: 'المستخدم',
    colAction: 'الإجراء',
  }
};

// ─── Tenant-Scoped Channels data ─────────────────────────────────────────────
export const CHANNELS = [
  { id: 't-wa', name: 'WhatsApp Business', icon: <MessageSquare className="w-4 h-4 text-emerald-500" />, iconBg: 'bg-emerald-500/10', enabled: true, aiEnabled: true, routingMode: 'Round-Robin', queue: 'Tier-1 Support', sla: '99.8%', volume: 14205 },
  { id: 't-wc', name: 'Web Chat Widget', icon: <Globe className="w-4 h-4 text-sky-500" />, iconBg: 'bg-sky-500/10', enabled: true, aiEnabled: true, routingMode: 'AI First Triage', queue: 'Farah Support', sla: '100%', volume: 8210 },
  { id: 't-em', name: 'Email Inbox', icon: <Mail className="w-4 h-4 text-violet-500" />, iconBg: 'bg-violet-500/10', enabled: true, aiEnabled: false, routingMode: 'Queue Dispatched', queue: 'Billing Operations', sla: '95.0%', volume: 4500 },
  { id: 't-vo', name: 'Voice / Call Center', icon: <Phone className="w-4 h-4 text-blue-500" />, iconBg: 'bg-blue-500/10', enabled: true, aiEnabled: true, routingMode: 'IVR Intents Match', queue: 'Inbound Line-1', sla: '98.5%', volume: 1020 },
  { id: 't-sm', name: 'SMS Alerts', icon: <Radio className="w-4 h-4 text-amber-500" />, iconBg: 'bg-amber-500/10', enabled: false, aiEnabled: false, routingMode: 'Broadcast Out', queue: 'Notifications', sla: '99.0%', volume: 0 },
  { id: 't-ig', name: 'Instagram Direct', icon: <Camera className="w-4 h-4 text-pink-500" />, iconBg: 'bg-pink-500/10', enabled: true, aiEnabled: true, routingMode: 'Social Queue', queue: 'Marketing Support', sla: '97.2%', volume: 620 },
  { id: 't-fb', name: 'Facebook Messenger', icon: <MessageSquare className="w-4 h-4 text-blue-600" />, iconBg: 'bg-blue-600/10', enabled: false, aiEnabled: true, routingMode: 'Social Queue', queue: 'Tier-1 Support', sla: '99.0%', volume: 0 },
];

// ─── WhatsApp Template Seed Data ─────────────────────────────────────────────
export const INITIAL_TEMPLATES = [
  { name: 'order_delivery_update', status: 'approved', category: 'Utility', lang: 'ar/en', usage: 14205, successRate: '99.8%', bodyEn: 'Hi {{1}}, your order {{2}} has been shipped! Track it here: {{3}}', bodyAr: 'مرحباً {{1}}، تم شحن طلبك رقم {{2}}! تتبعه هنا: {{3}}' },
  { name: 'refund_issued_receipt', status: 'approved', category: 'Utility', lang: 'ar/en', usage: 8210, successRate: '99.5%', bodyEn: 'Hi {{1}}, a refund of {{2}} has been issued for order {{3}}.', bodyAr: 'مرحباً {{1}}، تم إصدار استرجاع بقيمة {{2}} لطلبك رقم {{3}}.' },
  { name: 'ticket_escalation_alert', status: 'pending', category: 'Authentication', lang: 'en', usage: 420, successRate: '100%', bodyEn: 'Hi {{1}}, support ticket {{2}} is updated. Review response: {{3}}', bodyAr: '' },
  { name: 'monthly_promo_broadcast', status: 'rejected', category: 'Marketing', lang: 'ar/en', usage: 0, successRate: '0%', bodyEn: 'Get 20% off using coupon {{1}} on checkout!', bodyAr: 'احصل على خصم بقيمة 20% باستخدام الرمز {{1}} عند الدفع!' }
];
